### ISSUE TITLE
"Collection" Return Values

### ISSUE THREAD

**Issue by uv48uson** [uv48uson/amos-ss15-proj3#10]
Hey Gayathery,
is there any reason for the return type of `public ArrayList<CommitFile> getCommitFiles(String commitID)` is a ArrayList, while the return type of all other methods here are Iterables?
It's not really a problem but if there is no reason it might be better to have a common return type.

**Comment by uv48uson** [comment]
or maybe all return types could be lists!? beause we are anywy handling lists in the using classes, so it would be more convenient.

**Comment by TPolzer** [comment]
Iterators look reasonable as long as the actual values are generated on the fly.
If all contents are created before a method returns, I think Iterable or Collection would be most appropriate.

**Comment by gayathery** [comment]
It is now a list because there is a need to aggregate (add items to list )and manipulate the returned list. That is why only this method return type is changed from iterator to list

**Comment by TPolzer** [comment]
Where does this manipulation take place, I cannot see it?

**Comment by gayathery** [comment]
this manipulation will take place in future when we combine data from git and from the database where we will be maintaining additional linkages

**Comment by TPolzer** [comment]
But CommitFile objects are modifications, we are not adding anything like this from the database.

**Comment by TPolzer** [comment]
And even if you wanted to aggregate, this is exactly the situation where an Iterator that generates elements on the fly makes sense, as opposed to a Collection.

**Comment by gayathery** [comment]
For example if you see in getCommitFilesForRequirementID the following code 
ArrayList<CommitFile> commitFilesList = new ArrayList<CommitFile>();
		
     	Iterator<String> commits = vcsController.getCommitList();
	
     	commitMessageparser = new GitCommitMessageParser();
	
     	while(commits.hasNext()){
     		
     		String currentCommit = commits.next();
				
     		if(commitMessageparser.parse(vcsController.getCommitMessage(currentCommit)).contains(Integer.valueOf(requirementID)))
				{
					Iterator<CommitFile> commitFilesForAComit = vcsController.getCommitFiles(currentCommit).iterator();
					while(commitFilesForAComit.hasNext())
					{
						commitFilesList.add(commitFilesForAComit.next());
					}
					
				}
			}
can be replaced to the following (it is now not commited)

ArrayList<CommitFile> commitFilesList = new ArrayList<CommitFile>();
		
     	Iterator<String> commits = vcsController.getCommitList();
	
     	commitMessageparser = new GitCommitMessageParser();
	
     	while(commits.hasNext()){
     		
     		String currentCommit = commits.next();
				
     		if(commitMessageparser.parse(vcsController.getCommitMessage(currentCommit)).contains(Integer.valueOf(requirementID)))
				{
					ArrayList<CommitFile> commitFilesForAComit = vcsController.getCommitFiles(currentCommit);
					
						commitFilesList.addall(commitFilesForAComit );
					
					
				}
			}

if you know a better solution which is having lesser code complexity please tell me, then I can change to that too

**Comment by TPolzer** [comment]
I misunderstood you, I thought you wanted to have a streaming solution. If you want to do it the way you posted, Collection is really the return type of choice (everywhere):
``` java
Collection<String> commits = vcsController.getCommitList();

GitCommitMessageParser commitMessageparser = new GitCommitMessageParser();

for(String currentCommit : commits) {

	if(commitMessageparser.parse(vcsController.getCommitMessage(currentCommit)).contains(Integer.valueOf(requirementID)))
	{
		Collection<CommitFile> commitFilesForAComit = vcsController.getCommitFiles(currentCommit);

		commitFilesList.addAll(commitFilesForAComit );

	}
}
```
If on the other hand you want a true streaming solution, I think Iterable would be more suited.
``` java
Iterable<String> commits = vcsController.getCommitList();

GitCommitMessageParser commitMessageparser = new GitCommitMessageParser();

for(String currentCommit : commits) {

	if(commitMessageparser.parse(vcsController.getCommitMessage(currentCommit)).contains(Integer.valueOf(requirementID)))
	{
		Iterable<CommitFile> commitFilesForAComit = vcsController.getCommitFiles(currentCommit);

		for(CommitFile commitFile : commitFilesForAComit)
			commitFilesList.add(commitFile);

	}
}
```
Personally I would prefer the first approach right now, because it seems more convenient and as long as the whole Collection fits in the cache it also isn't a large performance penalty.

**Comment by gayathery** [comment]
Yeah I accept it and I will modify it. Thanks

**Comment by gayathery** [comment]
Now I have a question. . If collection is returned user will know what way it is internally implemented. For example whether a ordered or unordered data structure... isn't it?

**Comment by TPolzer** [comment]
What exactly do you mean by "ordered", something like a [SortedSet](https://docs.oracle.com/javase/7/docs/api/java/util/SortedSet.html)?

**Comment by TPolzer** [comment]
Apart from that (and its Map counterpart) the only other containers that explicitly expose information about their ordering are the explicitly unordered containers (e.g. HashSet), but neither is appropriate here I think. Instead the documentation should make clear what the valid assumptions about the order of CommitFiles in the Collection are (what are they actually - I cannot see any guarantees in the LogCommand documentation?).

**Comment by uv48uson** [comment]
i would agree that collection or set would be the best approach. Please come to a solution. The methods are widely used so some other methods and classes have to be adapted.

**Comment by TPolzer** [comment]
@uv48uson as long as those other methods store the result of the function call in a Collection they should be fine no matter what kind of Collection is actually returned.
