### ISSUE TITLE
If a code line of the file was affected by several requirements, the impact of the last requirement is not calculated

### ISSUE THREAD

**Issue by KatsiarynaK** [uv48uson/amos-ss15-proj3#101]
Example: the file Tracker.java was affected by req 37, than by req 70. 

the impact of req 70 is not calculated

http://gyazo.com/1b238907c9ea5affe8a15beb1fcf9223

**Comment by KatsiarynaK** [comment]
Before the commit is selected, the impact percentage looks OK

**Comment by gayathery** [comment]
The problem was not with last requirement. But impact percentage calculation was not done when a commit is selected in the application. With the fix, this is implemented
