### ISSUE TITLE
Req63: Traceability matrix, more digits still display after comma

### ISSUE THREAD

**Issue by kaobizz** [uv48uson/amos-ss15-proj3#106]
As a user, I want to see only one digit after the comma so that the GUI is not too cluttered.

**Comment by TPolzer** [comment]
duplicate of #96

**Comment by gayathery** [comment]
https://github.com/uv48uson/amos-ss15-proj3/commit/2c5888f01b8383e626cd2d0ec8822136e3e2af6f
