### ISSUE TITLE
x-artifacts?

### ISSUE THREAD

**Issue by TPolzer** [uv48uson/amos-ss15-proj3#11]
Why are some parts of the source code in this separate folder, which is not built or tested with the rest of the maven build? And why is it called x-artifacts? IMHO the images belong into /src/main/resources and the source files into /src/main/java. The jar should not be in the repository at all.

**Comment by uv48uson** [comment]
This source code is only there because Gayathery wanted it to hand-over to me. Dont worry i'll integrate it during my user story.
