### ISSUE TITLE
Eclipse plugin cannot be updated from eclipse

### ISSUE THREAD

**Issue by TPolzer** [uv48uson/amos-ss15-proj3#110]
As @gayathery said in #107 and @akaTJ and me discussed last week, it seems that if one uninstalls our plugin from within eclipse and tries to install the new one, (sometimes?) eclipse just uses the old jar.

After reading this:
https://www.eclipse.org/forums/index.php/t/96660/
I suspect that we would need to increase our version number.

**Comment by TPolzer** [comment]
https://www.eclipse.org/forums/index.php?t=msg&th=311066&goto=822551&#msg_822551
tells me that we can also just use the 'dropins' folder for testing.

**Comment by gayathery** [comment]
Yes we can use dropins folder.
And also, for every new release we should increase the version number .
