### ISSUE TITLE
Performance of application is very slow.

### ISSUE THREAD

**Issue by gayathery** [uv48uson/amos-ss15-proj3#113]
When any Requirement is clicked it takes nearly a minute to display its associated commits and changes. And after than when the file is clicked again it takes some seconds before the actual changes could be seen. I think as a user this will be annoying.

**Comment by GnuTalux** [comment]
What I saw is, that if req is clicked the same method will be called multiple times.

**Comment by GnuTalux** [comment]
do you think, that indexing is the key solution for our performance issue?
It think its now a lot slower :-/

I think, it would be better to discuss issues like this in team. Maybe then we could made up a well fitted solution?

**Comment by gayathery** [comment]
@GnuTalux  Actually the performance is not changed during indexing. I have calculated the timings and in fact the application in the first 10 minutes has not changed. and after 10 minutes it had lot improved. Because of the indexing implementation i do not find any performance issues in existing application. The complete indexing is taking place in a separate background thread. Regarding the same method being called multiple times...it is not because of the click event in the application. Please check where the other calls are originated. The original functionality was no way changed because of the new implementation. This is only an additional implementation to solve performance issues and it really solves it now in 10 minutes and I am working on to makes this time frame as short as possible. 
The actual performance problem is because of already existing architecture (refer https://github.com/uv48uson/amos-ss15-proj3/issues/118 ) and not because of the new implementation

**Comment by GnuTalux** [comment]
yes, the issue of "multiple times calling the same methods" originates before your indexer implementation.
I just mentioned it here, to inform everyone.

**Comment by gayathery** [comment]
@GnuTalux  when we take objects from the BL where relationship exists between them, the layers should not spoil their relationship, but current architecture dilutes the relationship between them and when it reaches the UI, again all relationships are being tried to be created. This is the root cause of the performance. this can be solved only by changing the architecture, but i do not want to take a risk at the completion of our project which can have adverse effects to existing functionality. So I am trying to solve it by some other means, like indexing

**Comment by yadimon** [comment]
maybe helps to improve performance:

the problem is still by Tracker#getBlame()
it takes much time, for wordBlame and jgit.diff
here example of indexing worker, after 13m of running.
http://sro-account.de/filez/amos/Call_Tree_13m.html
![profile](https://cloud.githubusercontent.com/assets/4369489/8397160/4d4d27e0-1dc2-11e5-9598-a020e73754d5.png)

here is the state after 20 minutes.
still 16th req in process...
http://sro-account.de/filez/amos/Call_Tree_20m.html

with profiling everything its much more slower, see the method times, for real values.

@TPolzer if you can, try to integrate some "read files" cache, "got diffs" cache or some other caches in the blame.

**Comment by gayathery** [comment]
@yadimon can you also please check the time taken for first indexing without profiling attached...so that i can get and idea. For me it took around 10 to 11 minutes for first indexing to complete. Anyway i am working on some more things to reduce this time. but as test it would be good if you can send me some information about the time takes at your side for indexing

**Comment by TPolzer** [comment]
So after recognizing that our application already has an overcomplex structure that makes it difficult to program tasks efficiently, you decided to just throw some more code at it without discussing this at all (there is not even a user story for this... even though it would probably make sense)?

We would gain a lot more speed if we actually reduced computing effort instead of caching it, RAM is only finite ;) and our application performs a LOT of redundant computations...

**Comment by TPolzer** [comment]
And if you actually want to cache things, please think about _what_, e.g. just collect blame for each file (that is expensive to compute and can be reused for a lot of other things).

**Comment by gayathery** [comment]
As provided in the commit of the indexing implementation, This is only the first implementation, I am still working on this. Of course it is not the final solution to improve the performance. BL processing should be improved too. our application triggers a lot of redundant computation, and the indexing feature avoids it as of now. because after indexing and when no changes are there to the underlying layers, it does not call the BL which was not the case earlier and this also reduces lot of time in translation BL objects to UI objects, because i am directly indexing the UI objects and parallely keep checking changes for underlying layer. This implementation can be switched on and off easily and it does not affect existing implementation at all

**Comment by gayathery** [comment]
@TPolzer There are also some serious performance issues with getBlame logic as told by @yadimon .I guess you are working on it to improve the performance with the correctness of the output. 

Apart from this, there are more performance problems still in the application , which i think must be improved.

**Comment by TPolzer** [comment]
It does not affect the current implementation at all, except that
- on a single core system (yes the do still exist), performance is now about halved,
- on a system with a spinning hard drive (a lot of them still exist), performance is less than half of what it was before
- the application crawls the whole commit history every 5 seconds after the cache is completed,
- our application now needs about 2gigs of ram while indexing our (tiny) repository.

Not to mention the not properly synchronized threads you have all over the place...

Also you spent a lot of work on caching things on the wrong layer, so if we really want to fix performance, you essentially did a lot of work that we can throw away later.

**Comment by TPolzer** [comment]
The issue with the getBlame logic is that it is called FAR too often, this is one of the few things that SHOULD really be cached but isn't...

**Comment by gayathery** [comment]
In my indexing implementation, i am caching the results of the blame operation. 
Because for example, a blame for one single requirement is taking approximately 12 seconds for just the few hundred files in our repo and I think first this has to be looked into before checking the number of times it is called. The root cause for this delay is the getBlame and the next issue with with the numerous layered architecture

**Comment by gayathery** [comment]
@TPolzer  I have implemented multi tasking for indexing with cached thread pools and now i find that as told by @yadimon the bottleneck for the performance is the getBlame. After implementing multi tasking now I found that for requirement with id "13" the time taken for getBlame is 6 minutes and the complete indexing is waiting for this to complete .so whatever optimization i do to cache something, it requires at least 6 minutes for this to complete indexing. so the key for the performance of the application is to fix the getBlame logic

**Comment by TPolzer** [comment]
So our repository contains 722 files and I need 870 getBlame calls just to click on requirement 70 and get the GUI responsive again (and that is just for one requirement, most of them do several hundred getBlames). No you obviously do not cache them.

**Comment by TPolzer** [comment]
If you did caching the right way, the count should never exceed 722, after clicking four requirements I am now at 3790...

**Comment by gayathery** [comment]
@TPolzer "No you obviously do not cache them." 

I do not cache them but in fact after indexing the get blame is not called at all.
you can try yourself, that after indexing, the application is in lightning speed just less than 1/2 a second for each click

**Comment by TPolzer** [comment]
Yes, because your cache circumvents broken logic in the gui that does hundredes of blames...

**Comment by gayathery** [comment]
i am not using the indexer before it completes indexing. In future this wiil be used even before it is completed. currently i do not use it before indexing is complete to avoid incorrectness in data

**Comment by TPolzer** [comment]
So instead of fixing broken things we just layer over them until it seems to work? Great.

**Comment by gayathery** [comment]
yeah that is right, i accept the gui makes hundreds of blames when indexing is not done. GUI should also be the main focus to investigate why blame is called so many times.. so I would suggest the following priority
1. stop unwanted blame calls from GUI
2. reduce the time taken by getBlame for some requirements where it crosses more minutes

and after this if we still face performance problems, we will continue with the indexing or if performance looks fine without indexing we can stop that. The indexing is not the solution to the problem. It will be there in the application until other issues are solved and when we come across a situation where our performance have improved then we can scrap the indexing..

**Comment by TPolzer** [comment]
It never takes minutes ;), it just sometimes happens to take hundreds of milliseconds.

**Comment by TPolzer** [comment]
And since it has to load all versions of the file it is looking at from disk, there are quite high lower bounds to its performance (that we have undoubtedly not reached, but I guess that at most a factor 3 is possible, maybe even just 2).

**Comment by gayathery** [comment]
you can check for Requirement id "13" and you can see yourself for the time taken for the tracker method getCommitFilesForRequirementID. It takes many minutes

**Comment by gayathery** [comment]
and one more thing to note is implementing cache for getblame can solve some performance problem but without additional mechanism to know when data should be used from cache and when to ignore cache because of changes to repository should be considered and we cannot always use the cache. and a mechanism like indexing checks the underlying data for changes...so we would need a similar functionality too..

**Comment by gayathery** [comment]
The problem with GUI calling the BL twice is finally fixed...it really ate away a lot of time because of the call stack of size around 40. But anyways finally fixed it in https://github.com/uv48uson/amos-ss15-proj3/commit/fc9478809ff142ed1f400af8927dcce77e0381ed

**Comment by yadimon** [comment]
just for info about "easy cache" here is aspectJ example. 944559a2d10a455be2bdcdd702fb8a14e1a3d19f
it looks like it work, by mvn install. But i cant setup it in Intellij IDE.
I try to add guava cache too.

**Comment by gayathery** [comment]
@yadimon we need to think about enabling cache because we have properly listen to changes in repo because if we cache everything the data shown in application will be out of date. that is why i implemented indexing instead of caching....

**Comment by TPolzer** [comment]
@gayathery if you insist on keeping this stuff please make it at least properly synchronized.

**Comment by yadimon** [comment]
@gayathery  we can purge caches ... e.g. by indexer event (like repo changed event)
@TPolzer calls of blame are not that much, and cache them maybe gives like 30% improvement for first run of `getCommitFilesForRequirementID()`.
After this run, or after the indexer is ready, caches makes everything faster.

So the problem of first run is still here, and exactly by req-13 its horrible.

Could it be a problem, that blames try to diff binary files, like images ?
the first big blame problems comes by : `x-artifacts\images\SpiceTraceability_SampleTestApplication.png` this commitfile.
for req 13.


@TPolzer 
at the GitBlameOperation you have this comment:
```
							/*
							 * Calculate the offset for the line after the
							 * edits before it. If performance becomes an
							 * issue, this could be done faster by
							 * traversing the cur.words and diff simultaneously
							 * and keeping track of the offset.
							 */
```

and the calculation there, with the png file, takes very long time.

more info about slow code:
vcsClient.getCommitFiles("ff8848c845e5339b93351c6e728bacc1bcdb2aa3").size()
is **86** ..
this commit ff8848c845e5339b93351c6e728bacc1bcdb2aa3 has only 11 changed files, but merge.
vcsClient.getCommitFiles("1df3c8021ceaa84c49493400124c4e6556c87317").size()  == **127**
on github: 1df3c8021ceaa84c49493400124c4e6556c87317 1 change, but a merge too.

probably the merges are somehow too hard for vcsClient.


--------------------
maybe this information helps you to improve the blame.

**Comment by TPolzer** [comment]
Merges are no problem, the problem I had overlooked are binary files, thank you @yadimon.

@gayathery since the caching done by @yadimon is faster, cleaner and threadsafe, could you please revert this little hack of yours?

Any ideas on how to reliably detect binary files (because obviously we do not even want to display them, and in consequence, computimg blame on them is unnessecary)? They could be made more tolerable for the time being by inserting
```
private final DiffAlgorithm diffAlgorithm = DiffAlgorithm.getAlgorithm(SupportedAlgorithm.HISTOGRAM);
```
this will speed up diff generation quite a bit, but I think it will lessen the overall quality of the diffs (Not an expert here). We could of course also just set a (user configurable) upper size limit for files we are looking at.

**Comment by gayathery** [comment]
@TPolzer  i have disabled the indexer. And for your information this is not a little hack for performance. It is a basic version of a well defined concept.. you can have a look into http://developer.android.com/guide/components/loaders.html

**Comment by TPolzer** [comment]
It is a very basic, very broken version of a well defined concept that you applied at a place where it absolutely does not belong.

**Comment by gayathery** [comment]
May be you did not understand the concept, It is not a broken version because it really satisfies the needs without creating overheads. There are no hard and fast rules where a concept should be applied and not.. It cannot be justified that this concept should not be used in this situation

**Comment by TPolzer** [comment]
I did some work on this, and by now the biggest performance issue that remains is that our interaction with DataSource is a mess... for nearly every interaction with datasource, O(number of reqs overall) time is consumed which is clearly unacceptable if we want high performance (reqs from "difficult" datasources like git should be cached, those from database should be fetched efficiently).

I also noticed that just clicking on a file in the listing when navigating from requirement calls methods from DataSource, while there is no reason to do so (we just want to blame + display the file contents). However since our control flow is quite complicated I have honestly no idea how to solve this without diving deep into the code.

**Comment by gayathery** [comment]
@TPolzer yeah you are right and i too am scared to touch the complicated code because it might have adverse effects if changed without having an in depth view of the code

**Comment by kaobizz** [comment]
The application is still so slow, it take more that a minute until a clicked requirement to open

**Comment by TPolzer** [comment]
Not "still" but "again", the new path code is quite slow.

**Comment by gayathery** [comment]
the actual issue was fixed already. the performance drop again is due to https://github.com/uv48uson/amos-ss15-proj3/issues/155 hence closing this issue
