### ISSUE TITLE
traceabilit matrix menu, starts 2 progressbars

### ISSUE THREAD

**Issue by yadimon** [uv48uson/amos-ss15-proj3#117]
click on menu Tools -> TraceabilityMatrix ->  TraceabilityMatrix by Impact: you will get 2 matrix progressbars at the same place. You can move one to see the another one.

**Comment by gayathery** [comment]
https://github.com/uv48uson/amos-ss15-proj3/commit/7a695d015368178ce9220cc882177be4d78ca35d
