### ISSUE TITLE
GUI Application architecture complexity - performance problem

### ISSUE THREAD

**Issue by gayathery** [uv48uson/amos-ss15-proj3#118]
These are the problems with our current application that is heavily causing performance issues:

- The average call stack for a single method  call in the UI is more than 20.
- To bring a new data from Business logic to UI , it needs implementation at least in 6 -10 layers.
- On an average of 15 application active user session , The methods in element converters alone takes avg 2 minutes of the process time, which is just doing data copying.
- I think for our logic this complexity is far too much.( i have calculated the cumulative time taken by these methods in the class session )
- The class constructors are overloaded with many UI calls and these classes are instantiated couple of times.

**Comment by yadimon** [comment]
any suggestions for a solution?

**Comment by akaTJ** [comment]
This seems to me like an implementation issue. How can I as a PO help?

**Comment by gayathery** [comment]
@akaTJ  I had wrongly assigned. 

@yadimon  I am also working on alternate solution to increase performance without changing current architecture

**Comment by gayathery** [comment]
https://github.com/uv48uson/amos-ss15-proj3/commit/3e3c81d7cbe7d093683816ba4fe13b3c6a672bcc

https://github.com/uv48uson/amos-ss15-proj3/commit/23470f618e064d29f492e30df0edf90147438206

https://github.com/uv48uson/amos-ss15-proj3/commit/617c8c0a5c3df995384e35fcd336a9c32c100930
