### ISSUE TITLE
Is class CommitFile really needed?

### ISSUE THREAD

**Issue by GnuTalux** [uv48uson/amos-ss15-proj3#119]
Hi guys,

I will work on Req-68. (remain linkage between moved/renamed files)

My approach is, to traverse over the current project directory and get required information
from existing filepaths.

e.g.: 
```Tracker.getAllFiles``` currently returns all ever existed files (old paths of renamed/moved) will be returned, which leads to the issue behind Req-68.
After my implementation ```Tracker.getAllFiles``` would return actual existing file paths.
(I will adapt all related methods, of course)

But unfortunately ```Tracker.getAllFiles```  geturns ```CommitFile``` objects.
Is it really required, that we stick on ```CommitFile``` or may I change it(, if its required)?

Who has an overall understanding of that layer of code? ( @yadimon @uv48uson ?)

**Comment by gayathery** [comment]
The Class CommitFile is required

**Comment by GnuTalux** [comment]
Ok, I understand, currently it is implemented to use that class.
But is it ok, to change it. Or does all algorithms base on CommitFile?

Let assume, we get all existing fie paths. How can I fit them into the current architecture?
Just instantiating a CommitFile object from file path, wouldn't be sufficient, is it?

**Comment by TPolzer** [comment]
The class `CommitFile` is used in a lot of places, but I do not see any necessity to have `getAllFiles` return `CommitFile` objects. The `getAllFiles` method is only used for listing files, and `CommitFile` is really not suited to that task.

**Comment by GnuTalux** [comment]
thanks, this is good to know!

**Comment by yadimon** [comment]
probably you should add something like `getCurrentFiles` that returnrs `File` and not `CommitFile`
than you have to adapt GUI for it (probably will be hard)

**Comment by GnuTalux** [comment]
oh my gosh.
this is really hard ^^ 

I am thinking about, to implement the user story in an other way...
My current approach seems easy at first sight... but as I try just to make my version of 
```getAllFiles``` (by traversing file system) to be shown on GUI, I have to modify and add lots of code. 
Now I reached the ```GuiController``` and the job isn't nearly done xDD

If this is not working today, I will try to re-implement the user story at next sprint.
