### ISSUE TITLE
Abstraction for "The Relataion between Req-ID and Commit-ID"

### ISSUE THREAD

**Issue by GnuTalux** [uv48uson/amos-ss15-proj3#12]
Hi Team,

we have discussed about the need of an abstract for "The Relation between Req-ID and Commit-ID" at the last meeting.
@yadimon: Did you want to implement something like this in respect to my interface "ReqCommitRelation..." (in branch "Req-13..")?

Currently their is that parser class/interfaces called "CommitMessageParser" and "Git...Parser".
(I understand, that "GitCommitMessageParser" isn't appropriately named).
In this case my suggestion is, to
implement that class as "CommitMessageParser", which will be just a simple "helper"-Class. I would also remove that interface. 

"interface CommitMessageParser' == deleted ==> .
"class GitCommitMessageParser" == renamed ==> "class CommitMessageParser"

What do you think guys?

**Comment by TPolzer** [comment]
```java
Map<Integer, Set<String>> getDependencies();
```
should really be
```java
Iterable<Integer> getDependencies(String commitID)
```
since we do not need anything but the ability to iterate over the requirements associated with one commit (The ability to have lookups does not matter for a single commit, because the list is small and for a number of commits we have to aggregate anyway).

With the same reasoning the `Set<String>` in `addFurtherDependency` should also just be `Iterable<String>`, although I doubt that adding dependencies should be part of this interface, because the classes adding dependencies will most likely be completely distinct from the ones querying single commits.

As to the `GitCommitMessageParser`, yes please rename it. :+1:

**Comment by GnuTalux** [comment]
To be honest, currently I am not using the "Get"-Method.  I could just remove it :smile: 

I thing, it sounds reasonable to change """Set"" by """Iterable""".

**Comment by GnuTalux** [comment]
@TPolzer I remember, why I used "Set"... to guarantee, that all elements occur at most 1 time.

**Comment by GnuTalux** [comment]
I think, we need the ability to iterate over all commits for given requirement, too.

I would change the interfaces to:
```
public interface ReqCommitRelationDB {
    void addFurtherDependency(Integer reqID, Set<String> commitIDs);
    void addFurtherDependency(Integer reqID, String commitID);
    Iterable<String> getDependencies(Integer reqID);
    Iterable<Integer> getDependencies(String commitID);
};
```

**Comment by TPolzer** [comment]
We definitly need both set and get methods, I just wanted to argue that they do not belong in the same interface.

**Comment by yadimon** [comment]
i think the set/add and get is the same DATA class, so we can switch to sql/orm/whatever by 1 (sub)class
but maybe we need some more higherlvl interfaces, like this one here, for just query the req-commit relation, and nothing else.
BUT!
things like data from commit messages, must be parsed before, and loaded to our database.
no project in the real world will contain requirements by commit messages (like we try to do now).
so add req by commit is just a feature we use, to make our linkage db easier to reconstruct.
I think we need to load all req<->comits from .git dir before. Than work with it.
probably we need some tool like "dataLoader", GitDataLoader. This loader must be able update data too.
Your opinion?

**Comment by GnuTalux** [comment]
This abstraction will be mandatory. Lets discuss this at our next meeting.
But I am looking forward to see your solution :)
