### ISSUE TITLE
Excess filea in the File column

### ISSUE THREAD

**Issue by KatsiarynaK** [uv48uson/amos-ss15-proj3#122]
1. click the requirement
2. click the commit
result - list of all affected files is displayed in the File column
3. click file name
result- file content is displayed in the Code column

However, some of displayed files have no relation to the chosen requirement
see example with req 68:
http://gyazo.com/9592f9d2b6b016173f9f95ace9b90112

**Comment by KatsiarynaK** [comment]
Probably the same problem:

http://gyazo.com/687d5f4bc8eb458d079d7eaaa0e38cbf

**Comment by TPolzer** [comment]
Should be solved by now.
