### ISSUE TITLE
The file was created by merge commit, but there is no affect of the corresponding req on the file

### ISSUE THREAD

**Issue by KatsiarynaK** [uv48uson/amos-ss15-proj3#125]
The file  amos-ss15-proj3-gui\src\main\java\de\fau\osr\gui\Components\javafx\ReqManagementPanel,java was created by “Merge first version…..” commit, but the impact of the req 61 on this file is 0%.

See example:
http://gyazo.com/7a991b25c0ac10f59450e939c6aea6b1

**Comment by TPolzer** [comment]
Same problem as #122. Closing.
