### ISSUE TITLE
Files have more than 100% impact

### ISSUE THREAD

**Issue by KatsiarynaK** [uv48uson/amos-ss15-proj3#126]
According to the traceability matrix, the following files have more that 100% impact in total by several reqs

amos-ss15-proj3-backend\src\main\java\de\fau\osr\core\vcs\AnnotatedLine,java
amos-ss15-proj3-gui\src\main\java\de\fau\osr\gui\Model\Collection_Model_Impl,java
amos-ss15-proj3-gui\src\main\java\de\fau\osr\gui\util\ElementsConverter,java
amos-ss15-proj3-backend\src\main\java\de\fau\osr\core\vcs\impl\GitVcsClient,java
amos-ss15-proj3-gui\src\main\java\de\fau\osr\gui\Model\I_Model,java
amos-ss15-proj3-gui\src\main\java\de\fau\osr\gui\View\ElementHandler\Linkage_ElementHandler,java
amos-ss15-proj3-eclipse-plugin\src\main\java\osr\adapter\PluginSPICETraceabilityMatrixAdaptor,java
amos-ss15-proj3-eclipse-plugin\src\main\java\osr\adapter\PluginSPICETrackerAdaptor,java
amos-ss15-proj3-gui\src\main\java\de\fau\osr\gui\View\Presenter\Presenter_CommitFile,java
amos-ss15-proj3-eclipse-plugin\src\main\java\osr\core\RegistrySettings,java
amos-ss15-proj3-gui\src\main\java\de\fau\osr\gui\Model\DataElements\Requirement,java
amos-ss15-proj3-eclipse-plugin\src\main\java\osr\core\RequirementMarker,java
amos-ss15-proj3-gui\src\main\java\de\fau\osr\gui\View\ElementHandler\Requirement_Detail_ElementHandler,java
amos-ss15-proj3-gui\src\main\java\de\fau\osr\gui\View\ElementHandler\Requirement_ElementHandler,java
amos-ss15-proj3-gui\src\main\java\de\fau\osr\gui\View\Renderer\RowHeaderRenderer,java
amos-ss15-proj3-eclipse-plugin\plugin,xml

**Comment by TPolzer** [comment]
Right now, this is intentional. Each line gets a 100% impact from all requirements that touched that line.

Impact calculation is scheduled to become more fine-grained in user story 26 (which is at the bottom of the product backlog right now).

**Comment by KatsiarynaK** [comment]
@TPolzer 
ok, thanks for the explanation
