### ISSUE TITLE
File is not clickable

### ISSUE THREAD

**Issue by KatsiarynaK** [uv48uson/amos-ss15-proj3#127]
I've tried several times during different sessions to chose the file and see its content:

amos-ss15-proj3-gui\src\main\java\de\fau\osr\gui\View\GuiViewElementHandler,java

but it is not clickable. At least on my PC

picture:
http://gyazo.com/56f2f452af90fb703dee10e66012a786

**Comment by GnuTalux** [comment]
This are non-existing files. 
As I can remember, @uv48uson has made them grey earlier.

**Comment by TPolzer** [comment]
I think this file exists, doesn't it?

**Comment by KatsiarynaK** [comment]
I can find some other examples, if necessary. Because that was not the only non-clickable file.

**Comment by uv48uson** [comment]
Seems like this greyed out is not workig anymore with the new UI design. But it doesnt matter since taleh and me are working on req-68 Introducing Path DataElementss tracking the files, so that there shouldn't appear files that dont exist anymore

**Comment by GnuTalux** [comment]
I think, that this could be solved now
