### ISSUE TITLE
Post traceability doesnt work

### ISSUE THREAD

**Issue by KatsiarynaK** [uv48uson/amos-ss15-proj3#128]
I have linked manually via the Linkage Management tab req 75 and the commit  "req-024 Implementation...."

result:

req 75 is linked with only one commit "req-75 fixed issue100.....". 

expected:

req 75 is linked with the commit "req-75 fixed issue100.....".  and with the commit "req-024 Implementation...."

**Comment by KatsiarynaK** [comment]
connected with #123

**Comment by uv48uson** [comment]
still not working? or only with this particular commt? Didn't we test the add linkage?

**Comment by yadimon** [comment]
its still to fix.
will be fixed by me.

**Comment by TPolzer** [comment]
For me this is still not working (and the error messages are erratic, sometimes empty, once pretending success while failing). Did you anybody actually test this?

**Comment by TPolzer** [comment]
I have looked further into this at the pattern seems to be that the first insertion (for one requirement) always fails with an empty error message, and the second one succeeds. Previously I also encountered cases where it tried to insert a requirement a second time (the database of course rejects that), but I think that those were solved with #157 (but not 100% sure).
