### ISSUE TITLE
TrackerAdapterWorker caches on the wrong level

### ISSUE THREAD

**Issue by TPolzer** [uv48uson/amos-ss15-proj3#129]
TrackerAdapterWorker caches outputs of Tracker. This is a lot of unneeded overhead, because the results of Tracker queries contain highly redundant data. Data should be cached on a data level, not on a query level.

**Comment by gayathery** [comment]
Unfortunately you did not understand the concept still, the indexing is having a specific data structure where it stores the consolidated data..and further queries use this data until the underlying data is not changed. and of course here only the data is cached and not the queries...the queries are just used to fetch data for this specific data structure..and this complete data structure can be persisted if required in future and can be used until there is no changes in the underlying system. Tracker queries may contain redundant data but what is stored in the internal data structure is not redundant unless it was required..

**Comment by gayathery** [comment]
to add to my above points...one thing to note is ---indexing is not caching...indexing can be extended to  persist across sessions while caching is not...indexing has its own data structure to maintain data based on the domain in which it is used while caching is not aware of such things...for example....windows file indexing or eclipse file indexing are not caching....they indey the files and uses the information until they are changed.....

and both of these concepts are quite different and not really worth the effort to compare them
