### ISSUE TITLE
Req-11 missing

### ISSUE THREAD

**Issue by uv48uson** [uv48uson/amos-ss15-proj3#13]
Hey Katja and Lukas,
I cant find requirement 11. Neither in the Product Backlog, the Sprint Backlog nor in the Feature Archive. Is this on purpose?

**Comment by akaTJ** [comment]
thanks for the information. this must have happened when we deleted US-11 and forgot to introduce number 11 back again! i will clean the document by Tuesday!

**Comment by akaTJ** [comment]
ok I just fixed it!
