### ISSUE TITLE
Tracibility Matrix progress bar not drawn

### ISSUE THREAD

**Issue by TPolzer** [uv48uson/amos-ss15-proj3#131]
Instead of a progress bar I just get a blank window. Can any of you reproduce this? Is this a general issue when using our Application with Linux?

**Comment by TPolzer** [comment]
The reason for this behavior is once again totally broken threading. I'll fix this.

**Comment by TPolzer** [comment]
@gayathery: This is the kind of bugs that happen when you do not take care with race conditions (#130).

**Comment by gayathery** [comment]
It's weird that race condition occurs based on platform.  It is very unlikely and it seems to be a new concept.

**Comment by TPolzer** [comment]
You are not even allowed to call anything in swing from other threads, because swing itself is not thread safe.
And actually it is common knowledge that race conditions are very dependent on the environment (machine/OS/load/etc.).
