### ISSUE TITLE
After click on the Home tab the user can not be back to any other tab

### ISSUE THREAD

**Issue by KatsiarynaK** [uv48uson/amos-ss15-proj3#132]
1. start the application
2. enter configuration data, click the Configure button
3. click the Navigation tab
4. do something on the Navigation tab (does not matter what)
5. click the Home tab
6. click the Navigation tab
result - nothing happens
expected - the Navigation tab is displayed.

ps. if I click the Configure button, I can continue working with the app. 

However, clicking the Home tab should not block the workflow

**Comment by gayathery** [comment]
https://github.com/uv48uson/amos-ss15-proj3/commit/35fc62b819383a2280c206b1ac27606bdb7a989c
