### ISSUE TITLE
Technical Poster Design 

### ISSUE THREAD

**Issue by gayathery** [uv48uson/amos-ss15-proj3#134]
Basic Things to have in the poster
1. Logo Placement - Elektrobit Logo and our application Logo
2. Architecture diagram
3. Technologies List 
4. Some technically important aspects of our project

**Comment by gayathery** [comment]
I am attaching the following image of architecture and some snapshots to be put in our poster. Please do give your opinions.
![app](https://cloud.githubusercontent.com/assets/11977313/8512186/30a9d540-2338-11e5-82e0-7d8be14c2660.png)
![arch](https://cloud.githubusercontent.com/assets/11977313/8512187/30bdd6d0-2338-11e5-9c81-46dedb503831.png)
![backend](https://cloud.githubusercontent.com/assets/11977313/8512189/30c668d6-2338-11e5-969e-653473c446af.png)
![eclipseplugin](https://cloud.githubusercontent.com/assets/11977313/8512191/30c6fe2c-2338-11e5-8259-fb60018a151a.png)
![home](https://cloud.githubusercontent.com/assets/11977313/8512190/30c68276-2338-11e5-8cf3-d6d8f40a41bb.png)
![matrix](https://cloud.githubusercontent.com/assets/11977313/8512188/30c59e9c-2338-11e5-99f9-ecdbd7353fe3.png)

**Comment by gayathery** [comment]
The architecture is just a overall view of our application layers.. not the exact classes involved..

**Comment by yadimon** [comment]
looks good, but some opinion:

nobody knows what is a presenter, element handler etc..
in architecture diagram, i would change UI to just BL adapter, view, controller, or one element like "ui mvc here"

The package diagram, i would remove, since it is too complicated.
Or make it simpler.

**Comment by gayathery** [comment]
@yadimon I changed it based on your suggestion. Thank you. 
The package diagram i meant was not to be in the foreground...may be something like a watermark in the background. what do you think?
If someone could help me in designing the poster, it would be better..
![arch](https://cloud.githubusercontent.com/assets/11977313/8512472/603a865e-2344-11e5-825b-abda688912f9.png)

**Comment by KatsiarynaK** [comment]
I would add an Eclipse snapshot as well, because it's better to show that we have both - app and IDE plugin

**Comment by GnuTalux** [comment]
yeah, looks great!
the second architecture diagram is even better... :-)
how can I contribute to this poster?

**Comment by gayathery** [comment]
Here is the technologies list as an image
![technologies](https://cloud.githubusercontent.com/assets/11977313/8512744/6e81f802-2351-11e5-81eb-2c1cedc0e7e0.png)

**Comment by gayathery** [comment]
Can some one use these pics and create a poster by arranging them together. the class diagram can be kept as a watermark (as matrix green color) in the background. The overall back ground can be black and all the other pics can be arranged in the foreground. If there is more space available, some text about project highlights can be put.

**Comment by gayathery** [comment]
this could be a background
![digital_matrix_neon_background-wide](https://cloud.githubusercontent.com/assets/11977313/8512986/17a2939e-235a-11e5-92ad-f61c173990f3.jpg)

**Comment by gayathery** [comment]
Here is the first version of the SD poster (High quality image is in my local) 

<img width="960" alt="poster" src="https://cloud.githubusercontent.com/assets/11977313/8513655/7de2eb30-2374-11e5-8086-c641c132e048.png">

**Comment by gayathery** [comment]
i will export it from the photoshop file to the required format as per specifications tomorrow

**Comment by GnuTalux** [comment]
hey, this looks great! well done @gayathery!

I would like to suggest a few points, if it is ok...

- the screenshot, which is at lower right corner, looks to sheared (deformed)
- the background looks interesting but to darkish and little bit overloaded

but if you don't have time and motivation anymore, current version is fine enough ^^

**Comment by uv48uson** [comment]
i think it's awesome. Thank you for your time gayathery. Mybe Taleh is right that tit's a bit overloaded but i think this makes it even better. One Poster could never show the whole software. That's how it is. And we can go in detail if someone asks.

**Comment by gayathery** [comment]
Thank you @GnuTalux & @uv48uson 
@GnuTalux i think in this picture that i had uploaded it is bit malformed because i did a print screen and sent...because the original image is 35 Mb..the PreFinal version is in the following link
http://www.studon.uni-erlangen.de/frm1221610_58015.html

The final version will soon be there

**Comment by yadimon** [comment]
looks good, but somehow too much, and not structured.
if you want to modify it again, i prefer such form like in this posters:
http://www.se.rit.edu/node/senior_projects/2009

The "technologies" pic for example, is ok, so people understand "here are the technologies, they used"
but all other parts.. i m not sure it will be easy to understand why, for what etc..

But as Taleh said, its nice even if you dont change anything anymore.

**Comment by gayathery** [comment]
I have uploaded the final version for printing. yet there is time till today evening to modify it. so may be some time is there for fixing any overlooked errors.
the copy of the final version is here in the following link http://www.studon.uni-erlangen.de/studon/ilias.php?ref_id=1221610&cmdClass=ilobjforumgui&pos_pk=166483&thr_pk=58015&cmd=viewThread&cmdNode=lr:en&baseClass=ilRepositoryGUI#166398
