### ISSUE TITLE
Master build is breaking on Windows

### ISSUE THREAD

**Issue by gayathery** [uv48uson/amos-ss15-proj3#135]
The master is corrupt and build is failing after the commit https://github.com/uv48uson/amos-ss15-proj3/commit/325508a8ed2f3561b30db7dd423735d93601516e 

Errors in 
testTraversWithoutIgnoring(de.fau.osr.util.VisibleFilesTraverserTest)

**Comment by TPolzer** [comment]
Ah I see now that in the refactoring branch of @GnuTalux (that I partially merged) there were tests that were not cross platform. Sorry.
