### ISSUE TITLE
Existing functionality is not working anymore

### ISSUE THREAD

**Issue by gayathery** [uv48uson/amos-ss15-proj3#136]
In our application now the following is not working with one of the recent commits. (this feature was working before the commits)

1. Select Requirement - Commits and files are listed
2. Select Commit - The corresponding files are not shown, it is still showing the complete set of files of requirement

**Comment by TPolzer** [comment]
I bisected this to 117eef386aed42a1ed862f0712f4c77482d2652a. Just looking at the diff, I have no idea why this breaks. Will look further into it. Any ideas?

**Comment by gayathery** [comment]
I am not sure about it. This functionality was added in last sprint by implementing instanceRequirement and setting its link in Commit object. May be this could help?

**Comment by TPolzer** [comment]
Actually no, this doesn't help, because instanceRequirement has nothing to do with it, it was introduced in f2b66b744702fc9cae903f2c2d8d2e4b61d3f503, but the functionality is we are talking about is already working in its parent, 2c5888f01b8383e626cd2d0ec8822136e3e2af6f.

**Comment by TPolzer** [comment]
argh, found it

**Comment by gayathery** [comment]
thats nice

**Comment by TPolzer** [comment]
I made the really stupid mistake of mixing up the two different `Commit` classes in my head.

**Comment by gayathery** [comment]
sometimes it happens but anyway finally you found it
