### ISSUE TITLE
Need help for adapting Tracker and VcsClient for new data type Path. (current it uses CommitFiles)

### ISSUE THREAD

**Issue by GnuTalux** [uv48uson/amos-ss15-proj3#138]
I need methods for Tracker, which returns Path instead of CommitFiles.
I will start working on it.
If someone has spare time, It would be nice, if we could split the work ^^

**Comment by TPolzer** [comment]
I would love to help, however I have no idea currently how to approach it, as I think @uv48uson and you are already working concurrently on the code? Is there any cleanly separable task(s)?

**Comment by TPolzer** [comment]
Helping would also be easier if the branch was buildable I think.

**Comment by TPolzer** [comment]
Since you closed this issue @uv48uson, is this code in a mergeable state?

**Comment by uv48uson** [comment]
see email
