### ISSUE TITLE
after "add linkage", selection of reqs, does not update commitslist. 

### ISSUE THREAD

**Issue by yadimon** [uv48uson/amos-ss15-proj3#139]
tab linkage Management -> do "add linkage".
go to navigation tab
select requirement, all commits shown every time.

**Comment by TPolzer** [comment]
Are you sure you pressed the refresh button? For me this is only occuring if I do NOT press the refresh button after adding linkage.

**Comment by yadimon** [comment]
@TPolzer you are right updated.

**Comment by gayathery** [comment]
https://github.com/uv48uson/amos-ss15-proj3/commit/a7f90b059f2d20d94ba829c477ee041b11ec3563
