### ISSUE TITLE
Different data

### ISSUE THREAD

**Issue by KatsiarynaK** [uv48uson/amos-ss15-proj3#143]
Could someone explain why the same code line has different linked requirements in plugin and in the app?

For example, Tracker.java the line number 191 in the plugin is related to req 26, and it is related to the reqs 26, 34, 35, 37, 40 in the app

http://gyazo.com/df614fced2db12163dcf16c39b4b09eb

![1](https://cloud.githubusercontent.com/assets/11986219/8550050/75c4e7d6-24ce-11e5-9f89-5b57f674a6cd.png)

the build was made today at approx 15.00. If required, I can find other examples

**Comment by TPolzer** [comment]
It looks to me like it is missing the added linkage from the database.
