### ISSUE TITLE
Traceability matrix contains negative impact data

### ISSUE THREAD

**Issue by KatsiarynaK** [uv48uson/amos-ss15-proj3#144]
Several example files:

http://gyazo.com/44e4388b4cd2747411dbc298fd2b6c3a

**Comment by TPolzer** [comment]
The reason for this behaviour is that in c64b54412cf446eebca35a8ce52389072ff93a2c I inadvertently changed how getCommitFilesForRequirementID() in Tracker.java reacts to non existing files. I would argue that this should not occur at all, but we can of course trivially change it to return 0 impact instead.
