### ISSUE TITLE
A method like *VcsClient::is_versioned(Path)* would be nice.

### ISSUE THREAD

**Issue by GnuTalux** [uv48uson/amos-ss15-proj3#147]
Hi guys,

I am thinking of writing a method, which returns a boolean for a given file path, which indicates its version-controlled or not.

Currently I am using *tracker::getCommitsByFile*, which is very unefficient.

I think, there must be a efficient way asking JGIT, if it knows a given file ;-)

Who knows, how this can be done via JGIT.

**Comment by TPolzer** [comment]
You can just iterate over all files under git with a TreeWalk, see https://wwwcip.cs.fau.de/~ca02dufe/apidocs/org/eclipse/jgit/treewalk/TreeWalk.html

**Comment by GnuTalux** [comment]
You mean the similar way as in *GitVcsClient::getCommitListForFileodification*?
thanks.

**Comment by TPolzer** [comment]
Actually no, because you want to iterate over files at one revision while GitVcsClient::getCommitListForFileodification iterates over revisions and uses a TreeWalk just to find the file.

**Comment by TPolzer** [comment]
http://www.programcreek.com/java-api-examples/index.php?api=org.eclipse.jgit.treewalk.TreeWalk

**Comment by GnuTalux** [comment]
Now I understand you. 
You mean, I can use TreeWalk to iterate over all version-controlled files.
Wow, this is nice!
So I don't need "is_versioned" and also don't need the DirectoryWalker anymore. ^^
