### ISSUE TITLE
Project Documentation 

### ISSUE THREAD

**Issue by gayathery** [uv48uson/amos-ss15-proj3#156]
Hosted a GitHub page for our documentation. Link to the site : http://uv48uson.github.io/amos-ss15-proj3/

I have already added 
- Video Manual for application usage
- Bill of Material
- Class and Package Details Document
- Yet to link User Manual   ( from @KatsiarynaK  )  

Please add  the rest of the documents in the https://github.com/uv48uson/amos-ss15-proj3/tree/master/artifacts/Docs
Finally, I could provide link to the published webpage.

**Comment by TPolzer** [comment]
This is not how github pages are intended to be used. This leads to interesting artifacts, like issues only being considered closed if their fixing commit gets merged into the gh-pages branch.

Furthermore, code documentation should really be generated automatically, not the html put under version control.

**Comment by TPolzer** [comment]
@uv48uson can you set the default branch back to master?

**Comment by uv48uson** [comment]
ähm, well im a little confused. Should i?

**Comment by gayathery** [comment]
if default branch is changed the web site wont work. you can see the documentation in https://pages.github.com/ and this is meant by gihub to keep the gh-pages along with the project.

**Comment by gayathery** [comment]
one sample example where they keep the doxygen generated documentation in gh-pages is https://github.com/m-a-d-n-e-s-s/madness/issues/104
there are so many git hub projects hosting like this.

**Comment by uv48uson** [comment]
well. so that's a no, i guess!? @TPolzer any objections

**Comment by gayathery** [comment]
thats a no from my side. we had already finished with the project from our side and 'closing issues' is just a minor issue

**Comment by TPolzer** [comment]
@gayathery if you had read the documentation you would know that it does not have to be the default branch.

**Comment by TPolzer** [comment]
But of course at this point it really is of no importance anymore, I agree

**Comment by gayathery** [comment]
@uv48uson please check that if you change the default branch to master, the website is working, if the website is working then you can keep the default to master itself

**Comment by gayathery** [comment]
@uv48uson i already checked it for one of my personal repository and having master as default branch is working. so please change it.. Thanks @TPolzer

**Comment by uv48uson** [comment]
seems like. so i keep master as default now

**Comment by gayathery** [comment]
This issue is an issue to reference for documentation
