### ISSUE TITLE
Type of requirement

### ISSUE THREAD

**Issue by yadimon** [uv48uson/amos-ss15-proj3#18]
I m just wondering,
if we use string for commits, why dont we use strings for requirements?

**Comment by uv48uson** [comment]
well until now commits are ids like this: 3j6b7k8n34h4b6k7 and requirements are digits so...

**Comment by yadimon** [comment]
so it can be for sure not a number because we dont know where they comes from in the future?
or, we can use NAME-ID relation, but than we can use commit id as Integer.
I preffer to use strings for now, before its not to much to change in code.

**Comment by uv48uson** [comment]
It'll probably change when we connect to jira for example. So i dont mind. But an extra relation seems to be overhead

**Comment by yadimon** [comment]
we use the strings now.
