### ISSUE TITLE
File indention

### ISSUE THREAD

**Issue by GnuTalux** [uv48uson/amos-ss15-proj3#19]
Hey guys,

my IDE is complaining about some files, because they have TABS instead of 4 SPACES.
What kind of indention should we all use?

**Comment by yadimon** [comment]
4 spaces sure. Pls use 4 spaces.

**Comment by uv48uson** [comment]
Using tabs gives freedom to the viewer to configure their editor as desired. I like my tabs to display as more than 4  spaces, whereas u like 4. This is not possible without use of tabs. We would battle spaces when we each format in our respective editor; tabs are not an issue; this is why they were invented

**Comment by yadimon** [comment]
pls use spaces
http://programmers.stackexchange.com/questions/57/tabs-versus-spaces-what-is-the-proper-indentation-character-for-everything-in-e

the argumens about view are agains tabs.
e.g.
```
void some_func(String bla1,
               String bla2,
               String bla3)
```
can be veeery different on different editors with different fonts and tab settings, if you use tabs.  
And it will be the same, if you use spaces.

**Comment by uv48uson** [comment]
well ok u are right there. There is no point in discussing this further. So 4 spaces. That's fine.
