### ISSUE TITLE
Testing does not work with submodule as intended

### ISSUE THREAD

**Issue by TPolzer** [uv48uson/amos-ss15-proj3#2]
Pulling in the test repository as a submodule does not work, because it only links the repository but does not create a new one. Please test on a _clean_ checkout of master.

I really think the data should just be copied.

@uv48uson do you want to fix this?

**Comment by uv48uson** [comment]
I cant really follow your discription. For me it works fine. On top of this in the pom file i specified that the whole data from TestRepository should be copied to the new directory. So linking is no option.

**Comment by TPolzer** [comment]
Please think about what you are doing:
What you specified in the pom file was redundant, maven copies all resources by default.
If you _properly_ checkout this repository (amos-ss15-proj3) and its submodule(s) then the .git file in the TestRepository will look like this:
```
gitdir: ../../../../.git/modules/src/test/resources/TestRepository
```
This is not something you can call jgit on (I think), and you can definitly not treat this _text_ file as a directory (as you did in your pom modification). Also as soon as you copy it, it becomes basically invalid, because it is a relative link.

Please do test on a clean checkout!

**Comment by uv48uson** [comment]
no this modification in the pom file wasnt redundant because before the .git folder was not copied because it is hidden. so calling jgit on it should work. i dont really got what u wanted to tell me with this path. since im accessing via the getResource method the path should look like this `${localrepo}/target/test-classes/Testrepo` and there will be a .git in there

**Comment by TPolzer** [comment]
Please execute (in a clean directory):
```
$ git clone git@github.com:uv48uson/amos-ss15-proj3.git
$ cd amos-ss15-proj3.git
$ git submodule init
$ git submodule update
$ mvn test
```
The expected result is that all tests pass. That was never the case (and still is not). And yes, hidden files are copied by maven.

**Comment by TPolzer** [comment]
Honestly, I'll just fix this myself.
