### ISSUE TITLE
I can't make pull data to eclipse

### ISSUE THREAD

**Issue by kaobizz** [uv48uson/amos-ss15-proj3#20]
Need sour help to pull data from repository :(

**Comment by GnuTalux** [comment]
Unfortunatly I am not using eclipse, but normally """git pull""" gradify your needs.

**Comment by kaobizz** [comment]
may be @gayathery will answer this question since she is using Eclipse

**Comment by TPolzer** [comment]
Can you you somehow elaborate on your problem? What is it you want to achieve?
If you update files on the disk (e.g. with git pull) and they do not appear immediately in Eclipse selecting the project and pressing F5 should do the trick.

**Comment by gayathery** [comment]
or else you can do by right clicking the Project and then selecting Team->Pull

**Comment by kaobizz** [comment]
This is msg I get when I pull
![capture](https://cloud.githubusercontent.com/assets/11990591/7462517/4dc54576-f2b2-11e4-94b3-dd343d9854ef.PNG)

**Comment by TPolzer** [comment]
This branch does not seem to exist in the repo, it sounds like you have this problem:
https://stackoverflow.com/questions/14033442/could-not-get-advertised-ref-for-branch-error-when-pulling-in-a-git-reposit

**Comment by TPolzer** [comment]
Since @kaobizz pushed to the repository today I guess this issue is fixed.
