### ISSUE TITLE
GUI filechooser does not show hidden directories

### ISSUE THREAD

**Issue by TPolzer** [uv48uson/amos-ss15-proj3#26]
This is an issue because on Linux all files with a dot in front count as hidden, including the .git folder.
Maybe the file chooser should look in the .git subdirectory if it does not find a git repository in the selected one?

**Comment by GnuTalux** [comment]
yeah, thats true. 
my workaround was to enter the .git in text input by hand.

**Comment by uv48uson** [comment]
should be fixed. I tried it for linux mint. worked fine.
