### ISSUE TITLE
apache commons io

### ISSUE THREAD

**Issue by TPolzer** [uv48uson/amos-ss15-proj3#3]
Is there any reason why we are using a _really_ old (possibly buggy) version of the commons io library?

**Comment by gayathery** [comment]
@Florian if you have no issues in upgrading the commons io,  we would providebaby fix this.

**Comment by TPolzer** [comment]
@gayathery the way you used the @ tag notified somebody unrelated, you have to use github usernames, i.e. @uv48uson.
