### ISSUE TITLE
Properties file content

### ISSUE THREAD

**Issue by uv48uson** [uv48uson/amos-ss15-proj3#30]
Guys there's a problem. I can not change the Requirement Pattern witch is used for some methods. For example ```getAllRequirementsforFile``` uses the default Pattern from the propertie resource. Nevertheless the resources are in generall read only. So ... there is the problem the pattern must be somehow passed to the parser.

**Comment by uv48uson** [comment]
for now i fixed it via a setPattern but maybe there is an other suggestion?

**Comment by gayathery** [comment]
another solution would be to overload the parse method...something like the following
public List parse(String latestCommitMessage) and
public List parse(String latestCommitMessage String reqPattern)

In the second method you can override the REQUIREMENT_PATTERN and use the user supplied one

**Comment by uv48uson** [comment]
i tried this at first but realized later, that this is no solution because the parser is used from a lot of different classes. So u have to change all of them using the overloading method and changing there interface too, to pass them the pattern.

**Comment by TPolzer** [comment]
This would not be the case if we just made a DataSource out of the parser and just passed it around as a configured DataSource. This is exactly the problem I was talking about in #28.

**Comment by TPolzer** [comment]
And I think ideally this DataSource should be immutable, so it would have to get arguments in the constructor.

**Comment by yadimon** [comment]
implemented args in constructor 36adc8e39ffb2aa0af05984dee98edd9d9d6b9bf

**Comment by uv48uson** [comment]
i'll close this issue since the content is the same as issue #42
