### ISSUE TITLE
Gui-Application dosen't behave as expected

### ISSUE THREAD

**Issue by GnuTalux** [uv48uson/amos-ss15-proj3#33]
Hi guys,

I have executed the ```de.fau.osr.gui.Application``` class to check, how it is working.

My problem was, that after choosing repo and enter Req-Parser-Pattern no "main" Windows appears.
The only thing I can see is a Application-Icon in my taskbar but not our application.

Could someone knowing the gui code check this?

**Comment by GnuTalux** [comment]
I have built our project via ```mvn package``` and executed our application via ```java -cp target/amos-ss15-proj3-1.0-SNAPSHOT-jar-with-dependencies.jar de.fau.osr.gui.Application```

**Comment by uv48uson** [comment]
which system are u running? can u try to make ```mvn test install``` . Are u sure u entered a corret repo (so the .git directory) and a proper pattern?

**Comment by GnuTalux** [comment]
I am working on Suse Linux and I selected the .git directory (otherwise I will get an Error-Message)
and I don't changed the default Pattern.
I retried it with ```mvn test install``` but the result was the same.
The Gui is somehow working, but after the Pattern-Dialog there is nothing to see.

**Comment by GnuTalux** [comment]
@yadimon @gayathery does GUI work for anyone else?
for me GUI is not working. 
What should I do?

**Comment by TPolzer** [comment]
@GnuTalux could you please try the test_resizable branch(1d67e192af2a3e0554371849c4e78e913f044cde), this could help.

**Comment by gayathery** [comment]
It works for me. I just pulled master and did a mvn:install . Run the jar
in the target.

It does show most of tge functionality in UI.

Lastest I could test the linkages

**Comment by GnuTalux** [comment]
@TPolzer thank you very much. It is working for me :-)
