### ISSUE TITLE
What will be absolute path of "DefaultPathToCSVFile"

### ISSUE THREAD

**Issue by GnuTalux** [uv48uson/amos-ss15-proj3#34]
Hi guys,

I am curios about the app.property "DefaultPathToCSVFile" which is currently defined as "./dataSource.csv".

If Tracker doesn't get a ```DataSource``` instance then Tracker will create a ```DataSource``` to store data at "./dataSource.csv" by himself. But will this be created within the working directory or the project directory?
Wouldn't it be more reasonable, if ```DataSource``` is created depending of repo file path?

**Comment by GnuTalux** [comment]
Ok, I see, that "dataSource.csv" will always be created within our project directory.

I had implemented, that "dataSource.csv" should be created at the parent directory of given repo directory.  But someone changed this.

**Comment by uv48uson** [comment]
oh. Probably i changed it. I'm not sure about it but whatever. Im sorry for changing it. That wasn't my intention. If i have the time by today i'll redo it, else we must live with it for now. I'm sorry again. I refactored the whole UI so maybe this was kind of a side effect  ...

**Comment by GnuTalux** [comment]
no, this not the problem. Its not a big drama :-)
I just noticed it and wanted to present a (maybe) better solution.
I don't think, that this would be a problem at review meeting.

**Comment by yadimon** [comment]
i commitet by fix branch this DataSource - repo dependency
18fbaddca6b91c41101b7a059885f1a8aea37829
