### ISSUE TITLE
Can you add "FilesSort_combobox" to GUI?

### ISSUE THREAD

**Issue by GnuTalux** [uv48uson/amos-ss15-proj3#36]
Hi Flo,

I have troubles inserting the sort-Combobox into GUI, please.
Somehow I am not correctly using the Layouter. Could you insert the sort-Combobox ```FilesSort_combobox``` into GUI.
I am working on branch  "req16_sorting_filename"

If someone else can also do this, feel free fixing this ;-)

Sorry for late issue.

**Comment by uv48uson** [comment]
np wait a minute

**Comment by GnuTalux** [comment]
thanks!

**Comment by uv48uson** [comment]
k. Is it already working?

**Comment by GnuTalux** [comment]
well done! 
When I read all the required code lines, which you have changed to just add a "simple" combobox, 
I am somehow disappointed of swing ^^ ... its quite better then Tkinter :'D
