### ISSUE TITLE
Definition of Done

### ISSUE THREAD

**Issue by uv48uson** [uv48uson/amos-ss15-proj3#37]
Since we already spoke about test coverage here are two tools im familiar with:
djCover: messures only statement and branch coverage
CodeCover: can also messure condition coverage
We can use one of those and define what kind of coverage our tests should have. On top of this, we could(i u want to) use metrixs to define whether code is somehow clean. Therefore we could use FindBugs to calculate kiviat-diagramms for our code.
Just some suggestions

**Comment by GnuTalux** [comment]
sounds interesting!

**Comment by yadimon** [comment]
pls check  
emma (old): http://emma.sourceforge.net/  + example http://www.mkyong.com/maven/maven-emma-integration-example/ too
cobertuna: http://www.mkyong.com/qa/maven-cobertura-code-coverage-example/

on windows, i got error with emma. cobertuna was ok.

check serenity too (looks good, but not updated, didnt installed it):
https://wiki.jenkins-ci.org/display/JENKINS/Serenity+Plugin

i think cobertuna is easy solution for now.

**Comment by KatsiarynaK** [comment]
Hello everyone, 

This week our team has to decide on Definition of Done for completing the tasks.

Here is a draft of our team's Definitions of Done, which we have to finish by Wednesday. Therefore, please, leave your comments/improvements/additions/ **by 6 p.m Tuesday, 19.05.15**.

Here are suggested criteria for Done tasks:
1.	Code is finished (all ‘to do’ items in code completed) 
2.	Code commented, checked in and run against current version in source control
3.	Pushing code doesn’t cause any errors
4.	There is 70% (?) of test coverage by unit tests, code passes all unit tests
5.	Passed Acceptance Criteria
6.	Release Manager checked if the code is meeting development standards (?)
7.	Wiki is updated
8.	All relevant discussions in Github are closed

**Comment by yadimon** [comment]
1. probably hard, because we have some not resolved over long time todos. (but possible to resolve it)
6. we need the code standards (like comments format and tabs/spaces)

**Comment by uv48uson** [comment]
@yadimon i dont think that coed standarts in our current form are a problem. It hink a user story should not be rejected if like the comments dont fit this excact form. Because u can read them anyway.

4: what kind of coverage? line coverage? whats about gui features?
1: probably not that easy. very related to 8
7: yes. this could really improve our wiki

**Comment by KatsiarynaK** [comment]
@uv48uson about #4, I dont know how to assess test coverage correctly) this is a suggestion, if you have a better idea for test cases, please, write.

@uv48uson @yadimon should we exclude #1 ? or rewrite is somehow?

**Comment by yadimon** [comment]
@uv48uson ok
6. development standards could be "no standards" or "low standards".
1 and 8 could be todo/duscussion should be...  **solely** . So only for this userstory exaclty, nothing else.
4. we can just use mvn cobertura:cobertura for simple line coverage for now.
cobertura generates the reporting about coverage at: ${project}/target/site/cobertura/index.html
so run it, and open the html file to see the coverage.
Now we have like 23%. The minimum coverage will depend on DoD.

**Comment by KatsiarynaK** [comment]
Final version

Definitions of Done:

1. Code is finished (all ‘to do’ items in code, which are related to particular issue, are completed).
2. Code commented, checked in and run against current version in source control
3. Pushing code doesn’t cause any errors.
4. There is 70% of line test coverage by unit tests (except for GUI features), code passes all unit tests.
5. Passed Acceptance Criteria.
6. Wiki is updated.
7. All relevant to particular issue discussions in Github are closed.
