### ISSUE TITLE
code highlighting doesnt work

### ISSUE THREAD

**Issue by yadimon** [uv48uson/amos-ss15-proj3#39]
e.g. our repo, req-010 -> fixed imports commit -> GuiController.java should highlight some imports.

**Comment by uv48uson** [comment]
Yeah. Seems weird. Actually only very few lines are highlighted. I already noticed the same. Especially regarding the newest commits. There should be a whole bunch of lines highlighted. Should i take a look at this beside i doesn't know about these AnnotatedLines or is there somebody else who feels responsible. Tobias can not fix this, can he?

**Comment by TPolzer** [comment]
Can you please post the exact steps required to reproduce this?
When I click on req-010 -> fixed imports commit -> GuiController.java I get all lines highlighted that were inserted in ef099470e9bd5bfa27200a2ff034fc82034f2d9d and f6eda902a49566c7116c6c0bf2ef02f096dbe46e.
Is your working copy clean?

**Comment by yadimon** [comment]
i compiled/started on both os windows (10) and linux (Ubuntu 14 vm) but still buggy. Compiled latest master with maven. Used empty dataSource.csv

**Comment by uv48uson** [comment]
well actually there might be a missunderstanding how tobias user story works. Howerever i'll change it so that the comparision will be from the latest commit before the selected comit nd the first one after this. Then all should work

**Comment by uv48uson** [comment]
just forget what i wrote in the comment i deleted. The understanding of the user story is fine. Nevertheless it doesnt work. It's really an obstacle right now

**Comment by TPolzer** [comment]
So this is still an impediment, but not an issue anymore? I could possibly fix this if somebody told me what is broken.
