### ISSUE TITLE
Comments format

### ISSUE THREAD

**Issue by yadimon** [uv48uson/amos-ss15-proj3#41]
is it ok that i change all the /* comments to /** ?
and that you possible using the standard format of comments? (just type /** ENTER over the method)
for tags see: http://de.wikipedia.org/wiki/Javadoc

why?

1. if we want to generate some kind of documentation at some moment, javadoc will need such format.
2. if you work with an IDE (eclipse or intellij) to get quick information (like F2 in eclipse or ctrl+q in intellij) about a method, this IDEs uses javadoc format too. So for better programming perfomance you need right format too.

**Comment by GnuTalux** [comment]
I can agree. I am already using this :)

**Comment by uv48uson** [comment]
shouldn't be a problem. i can u se them too from now on.

**Comment by uv48uson** [comment]
i changed a lot of them
