### ISSUE TITLE
No need for ```CommitMessageParser``` in Tracker.

### ISSUE THREAD

**Issue by GnuTalux** [uv48uson/amos-ss15-proj3#42]
Hi guys,

while I'm working on my user story (18 and 19) I realized, that somehow it would be easier, if
we change/refactore the ```Tracker``` not requiring a "requirement pattern" ```Pattern```.
Actually all functionality which uses ```CommitMessageParser``` could be moved to ```VCSDataSource``` or could be shared by ```VCSDataSource``` and ```VCSClient```.
I think after ```GUITrackerToModelAdapter``` has defined the ```CommitMessageParser``` with a specific Pattern, then the Pattern  does not have to be passed to ```Tracker```.

what do you think guys? 

Currently we are using different ```CommitMessageParser``` objects. Some of them are affected by a user specified "Pattern" some uses default pattern. The result is, that the GUI shows unexpected Req-IDs. (Because we always use the same req pattern, we don't noticed this bug)
I'm working on it.

**Comment by uv48uson** [comment]
well all fo the methods should be affected by the user specific pattern. Nevertheless i think the architecture would be borken if a so called adapter would define this parser. Therefore i suggest this to happen in controller and pass it in the contructr to adapter and then to tracker

**Comment by yadimon** [comment]
check the fix pls,  revert/add the code and close.

**Comment by uv48uson** [comment]
seems fine. i didnt try it out, but i assume u did.

**Comment by GnuTalux** [comment]
seems fine to me, too.

Thank you for fixing this. I would have done it by myself, but I wasn't sure, If someone doesn't like my suggestion. :-)

Nice teamwork dude!

Feel free merging it ;-)

**Comment by uv48uson** [comment]
it is already merged, isn't it?

**Comment by yadimon** [comment]
it is. @GnuTalux  you should close this issua, if it satisfied you :)
