### ISSUE TITLE
Need a search text field above requirement pane

### ISSUE THREAD

**Issue by GnuTalux** [uv48uson/amos-ss15-proj3#43]
Hi Flo,

I am working on user story 29 (search for requirement).
I will implement this in same way as sorting.
Searching will be realized by implementing a Filter, which will be passed to GuiModel.

I need your help in the GUI.
Could you add a search text field above the requirements, please?
It would be nice, if you could add event handling, so that, if text is entered the 
requirements list will be updated. For "activating" Filtering, you 
have to call ```public void setRequirementIDFiltering(Predicate requirementIDFiltering)```
with a ```new FilterByExactString("SEARCH TEXT")```.

Currently Filtering/Searching works only for "Navigate from ID".

**Comment by uv48uson** [comment]
so u only want the search field for id?
np witch branch?

**Comment by GnuTalux** [comment]
yes, just for the requirement id.
I am working in Branch "Req-29_search..."

If you does not have time for this. Informe me, please :D

**Comment by uv48uson** [comment]
done. fine like this?

**Comment by GnuTalux** [comment]
thank you! well done!

Unfortunately our GUI does not auto update itself. But I think, this is a separate user story ^^
