### ISSUE TITLE
Many functionalities in new UI not working in master

### ISSUE THREAD

**Issue by gayathery** [uv48uson/amos-ss15-proj3#49]
when i click a requirement id, earlier there was atleast data after sometime but now i do not see data for a long time

**Comment by gayathery** [comment]
this is not working for some patterns in UI
reqid to commit is working for default pattern but not from commit to file
For some pattern like Req-(\d+) even reqid to commit is not working

**Comment by gayathery** [comment]
@GnuTalux can you check this problem because the UI  was last changed by you

**Comment by GnuTalux** [comment]
sorry It was my fault. But now it should work.
