### ISSUE TITLE
Testing requirements

### ISSUE THREAD

**Issue by TPolzer** [uv48uson/amos-ss15-proj3#5]
I just stumbled over the section "3.2 Testing requirements" in the wiki.
My problem here is that it makes no sense to me, because all it does on the master branch is duplicate tests so they are carried out twice when testing. This was the reason I removed them earlier (without looking at the wiki as I should have...).
In general all tests should always pass on the master branch, so I see no reason to group them semantically.

**Comment by uv48uson** [comment]
I updated the wiki to the current code state.
