### ISSUE TITLE
Single Mouse Selection to List Selection

### ISSUE THREAD

**Issue by uv48uson** [uv48uson/amos-ss15-proj3#54]
Hey guys,
I want to refactor the MouseEventHandler wie have and transform them to ListEventHandler. This is partially necessary for my user story anyway.
This would affect the guiController, MouseEvent, guiModel and Adapter. However inthe the controller mouseEvent and model only the signatures and the parameters of methods call to guiModel would change. The most would be in adapter.
Since this is a lot of work(and im not available from friday to tuesday) , im not sure whether i can finish it.
Hope this is fine for u.

**Comment by GnuTalux** [comment]
if you just do this in your branch without merging unfinished states into master, It will be fine for me, of course. :)

**Comment by uv48uson** [comment]
of course in my own branch. I just wanted to inform u because that was what we agrred on in team meeting. if there is a bigger refactoring...

**Comment by yadimon** [comment]
i probably will wrap/switch all the panels to another panels, to make the border be resizable. But the access to the old listpanels should stay the same.
