### ISSUE TITLE
Migration to another UI Framework

### ISSUE THREAD

**Issue by uv48uson** [uv48uson/amos-ss15-proj3#55]
Once in team meeting we discussed whether we want to migrate from Swing to any other UI Framwork. I wondered whether this is still relevant. If it is, we should really make progress there, because most of our work now is Swing specific.

**Comment by gayathery** [comment]
I think we should stay with this UI framework, because even in the pdf file from our partner (shared for common understanding) it is specified as Windows builder as an option... So i think we should stay with this framework as we dont foresee any real problems

**Comment by gayathery** [comment]
Eclipse plugin  may be an additional to swing UI I hope.

**Comment by yadimon** [comment]
it could be very beautiful with JavaFX. But transfer so much work to another UI will be too hard. I think swing is acceptable for the b.partner.

Anyway maybe its useful to try (https://www.google.de/search?q=swing%2Bjavafx%2Bmigration)
