### ISSUE TITLE
I have changed CommitFile.hashCode and .equals

### ISSUE THREAD

**Issue by GnuTalux** [uv48uson/amos-ss15-proj3#57]
Hi guys,

I have to remove duplicates in file scrollpane.
I have changed ```CommitFile.hashCode``` and ```CommitFile.equals``` to 
achieve this.

```
	@Override
	public boolean equals(Object o) {
		if(!(o instanceof CommitFile)) return false;
		CommitFile ocf = (CommitFile) o;
//  	return commitState.equals(ocf.commitState) && oldPath.equals(ocf.oldPath) && newPath.equals(ocf.newPath) && commitID.equals(ocf.commitID);
		return newPath.equals(ocf.newPath);
	}
	
	@Override
	public int hashCode() {
//		return Objects.hash(commitState, oldPath, newPath, commitID);
		return Objects.hash(newPath);
	}
```

I think, as long as we don't really need the strictness of previous implementation,
we could go along with my changes.
I hope everyone is fine with this.

Currently I am working on branch "Req-37_selecting_multiple_commits"

**Comment by TPolzer** [comment]
Please do not do this, it is very surprising behavior and could cause unexpected breakage in the future.

**Comment by GnuTalux** [comment]
ok.
