### ISSUE TITLE
VcsController purpose?

### ISSUE THREAD

**Issue by TPolzer** [uv48uson/amos-ss15-proj3#6]
Do we really need all that stuff in the class VcsController? It looks like a factory for VcsClients to me (with a lot of boilerplate), so in consequence I think it should only consist of a (potentially overloaded) factory method.

**Comment by yadimon** [comment]
i wondered about it yesterday too.
i think Gayathery can explain what she planned fot the class. Maybe its not relevant already.

**Comment by gayathery** [comment]
VcsController is class just to provide a level of abstraction to handle multiple Vcs systems. It is just to provide extensibility to the functionality. It can also be useful (ofcourse by adding more functionality to this class) to handle multiple sessions if we plan to host the implementation as a service

**Comment by TPolzer** [comment]
That abstraction is already provided by the implementation of the VcsClient interface.
I think what you want to do would be best served by having VcsClient be an abstract class with a factory method.

**Comment by gayathery** [comment]
i accept that Factory method will provides the same solution...But in that case any additional functionality (like session handling) in the future needs one more layer which can be avoided if we have this controller. Another situation would be when we need to aggregate data from multiple Vcs. From a normal perspective, i do not find any problem in having this class. it neither creates any problem in design, implementation or with performance. In fact this itself is a normal design pattern very often used in development, the main purpose of it being extensibe and a providing scope for data aggregation

**Comment by yadimon** [comment]
the problem now we have to write anything twice. once VcsClient one Controller...
Things like sessions would come later, and if it comes, we have higher abstraction, like tracker, or maybe ui in the future.
i would refactor it to just a factory for our special GIT client. Is it ok?

**Comment by TPolzer** [comment]
I pushed a quick suggestion how this could be solved to a branch (2f3a25ad62e17cb96d5ce09673c85227839299ad).
I accidentally pushed it to master, that is why it was closed here, I have since repaired this, sorry.

**Comment by gayathery** [comment]
Ok Tobias. push it to master.. this is ok
