### ISSUE TITLE
Java Version+URGENT

### ISSUE THREAD

**Issue by uv48uson** [uv48uson/amos-ss15-proj3#60]
Hey guys,
I just wondered why we are using java 7 and not 8, since i wanted to use lambda expressions.
Normally using the newest version should never be a problem, so i just suggest migrating to java 8.

**Comment by GnuTalux** [comment]
I also would prefer java 8. The new features are very nice and provide shorter solutions.

**Comment by gayathery** [comment]
i would also prefer Java 8. These decisions I think we should have taken at the start of our project itself...but anyways better late than never...hope there are no compatibility issues

**Comment by uv48uson** [comment]
I adjusted this as part of my user story for now

**Comment by TPolzer** [comment]
Although the new features in Java 8 are really nice, I think it might not be a good idea, as it requires all users to have a Java 8 runtime environment.

@akaTJ @KatsiarynaK could you please ask the industry partner if using Java 8 is ok?

**Comment by yadimon** [comment]
i would like to use java 8 too.
but yes, the industry partner should accept it.

**Comment by KatsiarynaK** [comment]
ok, will ask next time
