### ISSUE TITLE
CSV Parser

### ISSUE THREAD

**Issue by uv48uson** [uv48uson/amos-ss15-proj3#63]
When adding new linkage to the project, which is printed into the csv file and removing the linkage later on by manually manipulating the file, i accidentally left a blank line in there. This will cause errors while reading the csv file next time. This bug is probably not important at all, but nevertheless i wanted to share the knowledge of it being there.

**Comment by yadimon** [comment]
it will be replced by DB. But csv will be loaded to db on start, so the bug is useful.

**Comment by TPolzer** [comment]
Closing, since the csv file does not exist anymore.
