### ISSUE TITLE
No clean way of including our maven managed classes in the Eclipse plugin

### ISSUE THREAD

**Issue by TPolzer** [uv48uson/amos-ss15-proj3#64]
I have done some research on how to include our "main" classes (+dependencies?) in the plugin:

https://stackoverflow.com/questions/8387359/external-jars-in-eclipse-plug-in
suggests to just copy the jar around

http://robertvarttinen.blogspot.de/2007/01/adding-third-party-jar-to-your-eclipse.html
one could also make a plugin from the jar that just provides the backend functionality

http://www.subshell.com/en/subshell/blog/Referencing-Maven-projects-from-Eclipse-plugins100.html
this guy is having exactly the same problem we have (so maybe we want his solution?), but the solution looks quite complicated

https://maven.apache.org/plugins/maven-eclipse-plugin/pde.html
suggests to use Eclipse to build the plugin, I have no idea how to integrate this without making building our project nontrivial.

At the moment I am undecided how to proceed and would be glad to hear some opinions (or better alternatives!).

**Comment by uv48uson** [comment]
For me the fourth possibility sounds the most reasonable. U are right, this will probably make our build process morre complicated but the rusult would be the cleanest way. On top of this: building an eclipse plugin with eclipse somehow is intuitive isn't it? This will probably preserve us from future issues with the integration.

**Comment by gayathery** [comment]
Simple solution would be not to refer any maven project and we create a loose coupling by using the jar file from our project as a direct dependency of the plugin project which makes solution simple and i do not think this is a bad solution. we should have three jar files then...one for the backend, one for the gui (which refers backend jar )  and one for the plugin..so that there is a clean layering...and there is no need to have the plugin as a maven project which makes life easier to create deployment packages directly.

If we deliver them as packages separately , it will extensible for future use.

**Comment by gayathery** [comment]
Though in your current solution to have 2 different maven projects , its tightly coupled to the one single jar. If your solution is to expose out jar now it contains gui also.

**Comment by TPolzer** [comment]
To cleanly deliver them seperately we would have to package them all as eclipse plugins.

**Comment by gayathery** [comment]
FIrst thing,  the UI jar  is depending on the backed project rather than the jar of the back-end. 

For my user story, the actual plugin project i have do mote that packing the jars. There are some more dependencies that are handled by eclipse.

So i am going to create a plugin project separately but will be using the back-end jar.

**Comment by gayathery** [comment]
There are more complication doing the eclipse plugin itself so don't want to add extra complexities using the maven.

**Comment by TPolzer** [comment]
So you want to package the jars into the plugin and not deliver them separately?

**Comment by TPolzer** [comment]
And please use the project I have already created in the Req-22 branch, you can use eclipse to manage it, but that way it remains automatically buildable (important for CI - and convenient).

**Comment by gayathery** [comment]
your plugin user story is different - you are delivering the existing application as plugin.

My part is a to create a plugin to add spice functionality to eclipse editors.

**Comment by yadimon** [comment]
maybe useful...
pleople building their plugins somehow:
like they here:
https://github.com/pulse00/Symfony-2-Eclipse-Plugin
or they 
https://github.com/angelozerr/angularjs-eclipse

looks like they use solution nr 3.

**Comment by TPolzer** [comment]
@gayathery the intent was for the Req-22 user story to build the "infrastructure" and for Req-23 to add functionality to that infrastructure.

**Comment by TPolzer** [comment]
Today I tried to implement the solution outlined in
http://www.subshell.com/en/subshell/blog/Referencing-Maven-projects-from-Eclipse-plugins100.html
I got as far as seeing that I had to add
```xml
<supportedProjectTypes>
    <supportedProjectType>eclipse-plugin</supportedProjectType>
</supportedProjectTypes>
```
to the `maven-bundle-plugin` plugin configuration for it to do anything at all, but then it messed up the plugin manifest in ways such that the `eclipse-plugin` packaging refused to build it the next time.

At this point I am kind of lost. I can't even find a clean way to have maven just copy that damn jar!?

**Comment by gayathery** [comment]
Figued out clean possible way to build and manage  plugin, feature and the updatesite with maven. 

The projects are in the master.

Thanks for your support guys I could use tycho to successfully complete the task.

**Comment by TPolzer** [comment]
@gayathery is there a reason you did not use the projects I created and did not remove them?

**Comment by gayathery** [comment]
I tried to use your project but its not ready to use stage and needed many
changes so I used a seperate one . When the new one could solve our task
and you still dont use the old one we can move to the new projects .

Was the project you started working for you?

**Comment by TPolzer** [comment]
It worked for me and Travis ;) - I'll just remove it.

**Comment by gayathery** [comment]
That would be nice. Yet your solution is my starting point to implement
tycho. Good work.

**Comment by TPolzer** [comment]
What is that eclipse-feature for? I only used a plugin and a repository.

**Comment by gayathery** [comment]
eclipse feature is something for packaging a list of plugin together and delivering it as feature. and repository for list of features. currently 
To Note: with my last commit i had changed some build output paths which i will refactor soon...
