### ISSUE TITLE
Exception: hibernate.cfg.xml not found 

### ISSUE THREAD

**Issue by GnuTalux** [uv48uson/amos-ss15-proj3#66]
Hi guys,

I got the following Exception:
'''
Exception in thread "main" org.hibernate.HibernateException: /hibernate.cfg.xml not found
	at org.hibernate.internal.util.ConfigHelper.getResourceAsStream(ConfigHelper.java:173)
	at org.hibernate.cfg.Configuration.getConfigurationInputStream(Configuration.java:2095)
	at org.hibernate.cfg.Configuration.configure(Configuration.java:2076)
	at org.hibernate.cfg.Configuration.configure(Configuration.java:2056)
	at de.fau.osr.core.db.HibernateUtil.getConfiguration(HibernateUtil.java:32)
	at de.fau.osr.core.db.HibernateUtil.getSessionFactory(HibernateUtil.java:50)
	at de.fau.osr.core.db.HibernateUtil.shutdown(HibernateUtil.java:63)
	at de.fau.osr.gui.Application.main(Application.java:11)
'''

My hibernate config is in following path:
'''amos-ss15-proj3-backend/src/main/resources/hibernate.cfg.xml'''

What path is '''/hibernate.cfg.txml'''? 
For me the heading '/' indicates root directory.
I think this is somehow confusing.

**Comment by GnuTalux** [comment]
If I run our application by my IDE "IntelliJ", then its working. 
But if I try to run it in my terminal, i will get the previously descried exception.

Working directory is: $PATH_TO_PROJECT/amos-ss15-proj3/

**Comment by GnuTalux** [comment]
But despite this, I can work on on the project :-)

**Comment by gayathery** [comment]
if the file is present in amos-ss15-proj3\hibernate.cfg.xml then it works
this can be because of problem https://github.com/uv48uson/amos-ss15-proj3/issues/67

**Comment by yadimon** [comment]
for eclipse users probably you have to look at this branch: 1419dc0620ca1eee08601e438ddc5cb262b5eeac

for intellij, probably need to get eclipse stuff and re import eclipse project.
or how i did:
in project view right click on 
...gui/src/main/java -> mark directory as : sources root
...backend/src/main/java -> mark directory as : sources root
...backend/src/main/resources-> mark directory as : resources root
...backend/src/test/java-> mark directory as : test sources root
...backend/src/test/resources-> mark directory as : test resources root

than add our hibernate.cfg.xml to ...backend/src/main/resources

just updated the ignore file for hibernate config (8aa1dd972ea50ade45cd9e61578edc9a8937bcc4).

**Comment by gayathery** [comment]
currently the code in 'master' is not debuggable in eclipse environment...the classpaths completely have problems and I am stuck up

**Comment by TPolzer** [comment]
'amos-ss15-proj3-backend/src/main/resources/hibernate.cfg.xml' should be the correct location, '/' refers to the root of the resources folder.

**Comment by TPolzer** [comment]
@GnuTalux it could be that your IDE build is interfering with maven, have you tried
```
mvn clean package
```
and then running the jar file in target/?
