### ISSUE TITLE
Urgent : Master is not buildable ,cannot debug because of build error

### ISSUE THREAD

**Issue by gayathery** [uv48uson/amos-ss15-proj3#67]
Project 'amos-ss15-proj3' is missing required source folder: 'src/main/resources'	amos-ss15-proj3		Build path	Build Path Problem
Project 'amos-ss15-proj3' is missing required source folder: 'src/test/resources'	amos-ss15-proj3		Build path	Build Path Problem

**Comment by gayathery** [comment]
may be this could be the reason for https://github.com/uv48uson/amos-ss15-proj3/issues/66
But i am not sure

**Comment by gayathery** [comment]
@TPolzer can you please fix the classpaths. i think somewhere it had got messed up during the project structure changes you had commited to master. I am not able to debug my code any more

**Comment by gayathery** [comment]
there are problems with class path because of moving the resources folder....application is in UI folder but the resources are not there. Please check before committing to master...it is blocking.

**Comment by TPolzer** [comment]
fyi: the primary build system is maven, it never stopped working.
If your eclipse build somehow breaks, just use `mvn clean package`.
