### ISSUE TITLE
Integrated Eclipse Plugin - without Maven

### ISSUE THREAD

**Issue by gayathery** [uv48uson/amos-ss15-proj3#69]
Eclipse offers simple way to develop and deliver the plugin ( Plugin development project , feature development project and update site. )

Should we integrate it as a Maven Project ( i don't find a way ) 
or can we develop  and deliver it without using Maven. ( we will use our project jar file inside plugin )

**Comment by TPolzer** [comment]
if you look at the branch I created for Req-22, building a plugin with maven is just as easy as with eclipse, the real problem is making the dependecy explicit (see #64).

**Comment by gayathery** [comment]
yeah that is right, i also meant mainly about the dependencies and also do you have any idea about packaging the plugins in maven...(i do not mean the jar) but to create a feature out of the plugin and to deploy a update site.. this is easy in eclipse without using maven

**Comment by yadimon** [comment]
i think build should be automated anyway, and nice to have it in travis too.
So maven looks like importarnt part of it.

**Comment by gayathery** [comment]
Its done with maven.
