### ISSUE TITLE
The backend jar is not fully usable as standalone

### ISSUE THREAD

**Issue by gayathery** [uv48uson/amos-ss15-proj3#70]
The back-end jar file is not usable independently. 

To product the problem , try to use the back-end jar in a different project . What i spotted is some repository errors.

Hope, it need to be build with dependency.

**Comment by TPolzer** [comment]
This was a conscious decision on my part, because I suspected that the third party dependencies can (and should) be pulled in separately in eclipse (I am not sure if this is true).

**Comment by gayathery** [comment]
This behaves differently in the plugin environment.  So for now I am using gui jar with full dependency later we have to find a way to use backend jar
