### ISSUE TITLE
IS it a bug or expected behavior ? - Some files show impact percentage & is grayed out  .

### ISSUE THREAD

**Issue by gayathery** [uv48uson/amos-ss15-proj3#71]
![image](https://cloud.githubusercontent.com/assets/11977313/8022058/a43965b8-0cbb-11e5-93ea-c2b2e471e41e.png)

Req- 63

**Comment by yadimon** [comment]
here is still but with start of app.
you have to setup working directory your amos project folder (cloned from github).
or start the .jar from this folder.
