### ISSUE TITLE
Architecture, objects how we will use it.

### ISSUE THREAD

**Issue by yadimon** [uv48uson/amos-ss15-proj3#72]
hi,
so i want to make the backend working with objects, like hibernate objects. So that UI can work with the same objects.
Last time the decision was:
 - use hibernate for db data retrieve/save
 - use own objects for Tracker bl, to combine hibernate and git data in one object.
 - use own objects in UI (the tracker objects, decorated, probably)

Does this mean, that we need composite data objects, like CompositeDataSource.java for DataSources, but for every data object, e.g. requirement, commit, file, line ?
So that it can be possible to write in tracker/ui: req.save() and all changes are saved to DB? or req.getCommits() and all commits for the req are returned from DB and Git?

**Comment by GnuTalux** [comment]
Is there a documentation about this architecture? A very simple UML or something else to get an overview about the new changes... (this would be very nice)

But as I understand facades or composites (as you suggested) could be sufficient.

**Comment by TPolzer** [comment]
@yadimon the decision we reached last meeting was that we annotate objects with their source instead of differentiating them by type.

**Comment by yadimon** [comment]
@TPolzer what does this mean? with examples pls.

**Comment by TPolzer** [comment]
This means that a persisting object has a field (probably an enum) that denotes it's source, and then the dao takes appropriate actions, e.g. if an object is to be deleted that comes from git we have to insert some kind of negative entry.

This is not the most beautiful design, but probably the one that needs the least amount of work.
