### ISSUE TITLE
resizeable JScrollPane and columns

### ISSUE THREAD

**Issue by GnuTalux** [uv48uson/amos-ss15-proj3#73]
Hi guys,

I am trying to found out, how we can implement the GUI, so the columns and JScrollPane are resizeable.  Unfortunately it is not possible to use JScrollPane within JTable, which was our first idea :-( ...
As Dimitry told last time, we can use nested JSplitPane.

I have found to finished implementations
 - https://gist.github.com/pocket7878/7673893
   - Just a "MultiSplitPane.java" File and very easy to use
 - https://today.java.net/article/2006/03/22/multisplitpane-splitting-without-nesting#resources
  - Provides a zip archive, which must be included into our project. Currently I don't know, 
how to add it to our project.

Now my question are,
should we use one of them,   or
should I implement our own class,   or
should we forget about "resizeable columns" and I try to help someone with its requirement?

**Comment by GnuTalux** [comment]
please see commit https://github.com/uv48uson/amos-ss15-proj3/commit/cb963b15c21223ee999db72daff4fb3abf262e67

**Comment by GnuTalux** [comment]
so far, I will reuse the MultiSplitPane.class for our current sprint.
As I see, I have to add few more code/functionality to fully achieve our needs and want, therefore I guess, it will be ok ;) ...
If someone is concerned about licensing troubles, please tell me.

**Comment by TPolzer** [comment]
What is the license for that MultiSplitPane.java?

**Comment by GnuTalux** [comment]
I don't know. I could not find anything about it.
