### ISSUE TITLE
UI Refactoring integration + DataElement Management

### ISSUE THREAD

**Issue by uv48uson** [uv48uson/amos-ss15-proj3#74]
I finished the Refatoring of the UI so far. But there's a problem: 
Until now our whole Tracker/bl logic is not handling our dataElements(Commit, CommitFile, Requirement, AnnotatedLine which are currently widely spread among the project packages) correctly and everwhere. I think this should change. Until now the logic is still working with Strings for Requirements for example; nevertheless i thought that this should have been fixed in one of the user storys 50,52,53,43 last sprint (maybe i missunderstode them our u found a better solution). To integrate the refactored UI in the project this need to change. Unfortunately the changes must start much deeper than i thought, since the dataSource classes are affected too.
Concerning these changes i contacted dimitry via email yesterday evening but he is not reacting so far. So here is my question: How should i handle the problem right now? 
Normally i would just start to refacter the affected bl classes too, but here this might interfere the management of dataElements throughtout the whole project, scince the transformation into objects shouold start right after caching the data from the db. Unfortunately i'm not that fimiliar with the current db and deo object solution. And your ideas concering the data management on higher levels like bl. 
I'm sure u all did good work, so this should not criticise any of you. Nevertheless i think we should face the current (not that good) solution and improve.

**Comment by GnuTalux** [comment]
I also think, that this refactoring requires changes at nearly all layers. So this could lead to many conflicts, when you try to merge.
Maybe it will be better, if we put your changes at the beginng of next sprint...
But I am not sure.
Unfortunately, we will get our last feedbacks at wednesday :-/

**Comment by gayathery** [comment]
Yes it is a huge refactoring. I even think of some more improvements in the
backend code. The code is of little useful now to be used in another UI.

For timebeing I copied the Ui methods to backend which would have spead the
ui data elements that serves to give requirements to line number mapping.
Reg refactoring:
Its depends on how much you could work for this sprint ,still maintaining
the state of the builds.

On 9 Jun 2015 00:04, "Taleh Didover" <notifications@github.com> wrote:

I also think, that this refactoring requires changes at nearly all layers.
So this could lead to many conflicts, when you try to merge.
Maybe it will be better, if we put your changes at the beginng of next
sprint...
But I am not sure.
Unfortunately, we will get our last feedbacks at wednesday :-/

—
Reply to this email directly or view it on GitHub
<https://github.com/uv48uson/amos-ss15-proj3/issues/74#issuecomment-110155862>
.
