### ISSUE TITLE
CSV Parser

### ISSUE THREAD

**Issue by uv48uson** [uv48uson/amos-ss15-proj3#8]
If anyone needs the CSV Parser i wrote in PublicTestData, please inform me. Otherwise i would clean up the code soon. 
I seperatly contacted Taleh and Rajab for this, because i thought this might only be interesting for their user story. So i assume that nobody else needs it at the moment. Please inform me otherwise.

**Comment by GnuTalux** [comment]
I think, I could use them. You can delete the code, because I have my own copy in my branch. 
I would move your CSVParseraClass into pckage parser. Do you think, this is possible?

**Comment by uv48uson** [comment]
Ok well. I think you might make both so that there is an consistent 
state. Just move the code u need to your package and delete the code 
from PublicTestData.
Thanks
Flo

Am 30.04.2015 um 12:12 schrieb Taleh Didover:
