### ISSUE TITLE
Requirements to file linkage

### ISSUE THREAD

**Issue by KatsiarynaK** [uv48uson/amos-ss15-proj3#80]
Basically, the customer doesn’t require the linkage between req. and file itself, but what he really wants is that the soft could trace and analyze changes on the level of each code line (remember the first meeting with the industry partner), req to file linkage is just a means for implementing the feature.

What the industry partner wants is that the soft could analyze the following changes:

SITUATION 1

There is a file A with 10 lines.
The lines 1 through 10 of file A were written based on req 1.
Than the line 1 was changed based on req 2.
Than the lines 1 and 2 were changed based on req 3.
Not only the traceability matrix should indicate that the degree of correlation between the file A and req 1 is 100%, between file A and req 2 is 10%, between file A and req 3 is 20%, but also further analysis must be done.

The soft must analyze on the line level that the req 1, req 2 and req 3 have affected the line 1. At the beginning, no sophisticated algorithm or any fuzzy logic is required. Simply there must be info that each req has 33.3% of impact on the line 1. 
Respectively, the line 2 has 50% of impact by req 1 and req 3.
The lines 3 through 10 have 100% impact by req 1.
Later the analysis logic may be improved.

SITUATION 2

There is a file B with 3 lines.
The lines 1 through 3 of file B were written based on req 1.
The correlation between each line and reqs looks as follow:
Line 1 – req 1
Line 2 – req 1
Line 3 – req 1

Than the line 2 was changed by req 2.
The correlation between each line and reqs looks as follow:
Line 1 – req 1
Line 2 – req 1, req 2
Line 3 – req 1

Than the lines 1 and  2 were changed without any req.
Correlation between each line and reqs looks as follow:
Line 1 – req 1
Line 2 – req 1, req 2
Line 3 – req 1
(staid without changes)

Than the line 1 was moved to the line 3. 
There are two possible implementations of moving: simple and sophisticated. 
Simple is based on “delete/add” logic, the correlation between each line and reqs looks as follow:
Line 1 – req 1, req 2
Line 2 – req 1
Line 3 –  -- 
(the soft thinks that line 3 was inserted without any req)

Sophisticated is based on “move” logic, the correlation between each line and reqs looks as follow:
Line 1 – req 1, req 2
Line 2 – req 1
Line 3 –  req 1
(the soft recognized that line 3 is actually line 1, it just was moved)

Sophisticated way is preferred, but probably is more difficult for implementation.

Back to req to file linkage. The industry partner said that he don’t want that we spend 2 weeks on Git Blame implementation, but he still wants that out software could analyze the above situations. 
Could you come up with any other possible way of implementing the functionality?

**Comment by yadimon** [comment]
Here is general structure we can use, to handle non changeble data (like git or gira), and change it by rules.

![structure1](https://cloud.githubusercontent.com/assets/4369489/8116797/69b1d5ac-1084-11e5-8623-8e75471e595b.png)

**Comment by TPolzer** [comment]
@KatsiarynaK isn't this example exactly what you said in #79?
@yadimon I think the mutable DataSource should also be a DataSource, Tracker was meant as a facade and IMHO should not come into play here.

**Comment by gayathery** [comment]
I am really sckeptical whether it really addresses the actual requirements of the industry partner.

**Comment by KatsiarynaK** [comment]
@TPolzer yes, the first example illustrates #79

@gayathery could you clarify your concerns?
