### ISSUE TITLE
New architecture (new BP reqs), your opinion.

### ISSUE THREAD

**Issue by yadimon** [uv48uson/amos-ss15-proj3#81]
Because of new requirements from BP, we have to build new logic of the software.
I cant get it alone, and want to ask you how you see it.

We need somehow magically track the impact, by every commit. Even by moved files. We have to define what lines are changed, not added/removed (maybe jgit helps)

for now i think that we need at least something like this (pseudocode):  
    
```java
State GetCurrentState (){
    State impactState = getStateByFirstCommit();
    for (Commit commit: commits) {
        impactState = calculateState(impactState, commit);
    }
    return impactState;
}

State calculateState(State stateB4, Commit commit) {
    //returns new modified state by one commit more (or modifies it)
    //commit is used to get changed lines
    //here we get linkage information for each line changed by this commit!
    //(from git, from jira, from rules)
    //or this lines-req relation information will be integrated in the commit object already,
    //so we can calculate the new state of all lines
}
```

The `calculateState` method is where we have all the hard logic to define whats moved whats changed, how to track and merge the requrements influence.
For beginning, we just track added lines, and removed line maybe. So we get similar results like we have now.

from the `CurrentState` we can get all the lines percentages per file etc.

Your opinion to it?
  
  

----------------------------------------
The second problem is the architecture of the software.
here is probably one of solutions ([link](https://drive.draw.io/#G0B2aj6Drx4nxPZVBLVUNjLV81T0k)):

![architecture v1](https://cloud.githubusercontent.com/assets/4369489/8137714/74bcf6fe-1145-11e5-8f45-119210e6e39a.png)

now i need your criticism, solutions and opinion :)

**Comment by TPolzer** [comment]
I am already in the process right now of reimplementing the blame logic so that we can track for each word in which commit it originated. What you are suggesting is essentially blame for a linear history.

**Comment by yadimon** [comment]
it should: track merges, moves, line changes (not only added/removed) and what changes (probably what you do now with words) and know about rules, like "this line is not the requirement by this commit" or "this line will be only the 1 requirement all the time, until removed"
Do you thinks its possible by your implementation? (not now, but later)

**Comment by TPolzer** [comment]
A first implementation will only track words, detecting renames should be easy to add afterwards.
On the other hand I do not know how to add line copy / move detection logic, but when we have a base implementation we can later add bells and whistles.
The blame logic will not be responsible for tracking things like removed requirements, it will just tell you what commit created a word.

**Comment by yadimon** [comment]
ok, i see, we talking about different things.
you talk about blame only.  We have to know about moved/changed lines etc.
i talk about all in one, blame + logic of req-line relation by every commit.
This is what should be done too, independent of blame, but dependent on rules, git commits, jira info.
Slowly i see the one possible solution :)
*edited pseudo code again*

**Comment by GnuTalux** [comment]
how can I contribute? Who is doing what?

**Comment by yadimon** [comment]
for now its just a decision, if the architecture is ok.
Tobias do the new blame logic.
Others, dont know. I would like to implement basic architecture without logic. And try to adjust it with new GUI branch. 
The hard logic is todo for everyone.
But first, is it ok? Do we want begin with the architecture? Maybe some better solutions? maybe some mistakes in this architecture?

**Comment by gayathery** [comment]
Its not a good idea to refactor or change the architecture right now. 
 
First we try to solve the problem , like the logical way to solve.

The new architecture would bring more confusion rather solving the current  problem.

**Comment by yadimon** [comment]
@gayathery this architecture is needed to solve the problem :/
it does not change tracker so much (so no big refactoring)
we don't need rules for now.
we don't need hard logic for now.
i can implement simple version of it.

**Comment by uv48uson** [comment]
For now i'm a bit worried. I'd really like to integrate the new UI design this sprint. Otherwise it will be more and more upcoming work each sprint to keep it up-to-date. Unfortunately this is dependend on the state of the BL refactoring. So, whats the current state and idea of integration...?

**Comment by yadimon** [comment]
i ll try to integrate today, with or without new bl. (tracker will be like the same)

**Comment by gayathery** [comment]
@yadimon  I am not able to fit in the architectural changes suggested by you. But if you are able to solve any of the problems as requested by the Industry Partner its well and good.

**Comment by gayathery** [comment]
@uv48uson  I would suggest you could commit your work if it complies to our agreements.
Guys working on big changes please consider to incorporate Florians changes. Ones after you make changes it would be very hard for Florian to integrate his changes.
