### ISSUE TITLE
State of our application after the last commit for Req-37 

### ISSUE THREAD

**Issue by gayathery** [uv48uson/amos-ss15-proj3#83]
Team, 

The application is missing many features and some not working after the last big refactoring

Here are the problems i found out 

1 . Search requirement by requirement ID not working
2.  Navigate from commit is back. ( which we removed ) 
3.  Navigate from Requirement ID is not working ( which was developed 4 sprints ago and its our core of the application functionality ) 
4. Add Linkage is still there ( which is suppose to be moved to Menus ) 
5. I could not see the tree structure files display anymore.
6. One traceability Matrix works . But not useful because of the data is wrong.

The last commit says some commit message , pertaining all these ( > 100 files ) changes are for Req-37 . But i could not find this feature in the application working. 

We still have only 3 + 1 sprints to go for demo.  I don't see much features going on since last 3 sprints . Every time a major refactor affecting avg. 10000 lines of code but no feature .

**Comment by uv48uson** [comment]
Dimitry merged this yesterday evening. I thought he would merge to a seperate branch req-37. but no we must work with this. Im going to fix as many bugs as possible the next 2 days. Hope its up to date until wednesday.

**Comment by GnuTalux** [comment]
I thnik, we are overdoing refactoring.
Currently the resize-able gui columns are removed and
I cannot effectivly work on the project. 

In ```RegistrySettings.java``` the class ```AppProperties``` cannot be imported
and in ```amos-ss15-proj3-eclipse-plugin/pom.xml``` there are
invalid tags. My editors says, that ```<environments>``` within ```<configuration>``` is not allowed.

I have re set up my project structure in intellJ, but it does not solve the import-issue

**Comment by GnuTalux** [comment]
I know, that I have to create a JAR-Archive at ```amos-ss15-proj3-eclipse-plugin/lib/amos-ss15-proj3-gui-1.0-SNAPSHOT-jar-with-dependencies.jar```.

**Comment by GnuTalux** [comment]
@uv48uson Do you need some help?
Which problems are still open?

**Comment by uv48uson** [comment]
im still working on updated branch req 37. The branch is in the same state of master. im currently trying to fix everything there. If u have spare time i would appreciate your help. just pick up any of the points gayathery wrote or anything else u noticed, which is not running yet. thx

**Comment by yadimon** [comment]
sry, but must be in master, otherwise all the work should be applied to the new architecture again and again .. every time double work. If big refactoring, that asap, so everyone can work on it. Or just no refactoring (maybe later). 
UI design is not fully merged yet, pls wait until merge is ready if you work with/on UI.
Tracker will be the same (with deprecated old functions, and new), after structure refactoring.

**Comment by GnuTalux** [comment]
ok, if it is ok, I would start with the issues 1-3.
If you have already done any of them, I would just move to the remaining isusses. I will start working on this tomorrow.
Hopfully you will inform me :)

**Comment by uv48uson** [comment]
issue 5 done.
i'll try to understand the problem with 6.
dimitry, if u can pls have a look at 4 since this was initally your user story

**Comment by GnuTalux** [comment]
I am trying to add MouseListner for 3). 
unfortunatly I don't really understand the new architecture.
Where I have to put/define a MouseListner.

**Comment by TPolzer** [comment]
@GnuTalux please do not define a `MouseListener`. `ListSelectionListener` is what we want here.

**Comment by GnuTalux** [comment]
ok. @uv48uson will take care of this :-)

**Comment by GnuTalux** [comment]
fixed 1) 2) and resizeable scrollpane eb7836bf00bc25f211fdff50e56b741f7edaaa4a
(I made a mistake and wrote in commit message "Issue-83" instead of "Issue 83",
therefore I put it here by hand)

**Comment by uv48uson** [comment]
I fixed 3

**Comment by uv48uson** [comment]
one problem: there seems to be a bug in getting commits from tracker. therefore commits are not shown right know. Dimitry can u hava a look at the required tracker methods. or i think there is a Requirement class internal method called getCommits with is not wirking!?

**Comment by uv48uson** [comment]
fixed 6

**Comment by uv48uson** [comment]
@yadimon can u please have a look at the getCommits method and wether it's working correctly!?

by today evening i'll commit to brnach 62 a tabbed version of the ui. to show the usage of the new architecture. There will be an additional tab for requirement details, as u requested. Pls have a look at it for future implementation.

**Comment by uv48uson** [comment]
committed. not correctly formatted. I thought this would not be important for demonstration

**Comment by yadimon** [comment]
@uv48uson  getCommits  should work properly. It gets commits from VCS, like before.
But we tried to have hibernate-like objects. And it will be very very hard to achieve.
So things like `req.getCommits()` will be not possible. Its hard to generate bidirectional linkage between our generated objects. (req has commits, each of his commit has reqs, each his reqs has commits etc. .. )
That means, to get a `commit` from `req`, we will not use `req.getCommits().filter(commit)` but `tracker.getCommitsByReq(req)`
If somebody has better solution, let me know.
i ll refactor the tracker (the api will be still the same, but try not to use things like req.getCommits())
And thx for Tab example!

**Comment by uv48uson** [comment]
np. But in the tracker adapter u wrote there is the function req.getCommits() used i think. Can u fix this?

**Comment by yadimon** [comment]
fixed by 7214def344fe8e90d0c38fece5a28650670ddbad
