### ISSUE TITLE
How can I install our plugin in eclipse

### ISSUE THREAD

**Issue by GnuTalux** [uv48uson/amos-ss15-proj3#84]
Hi guys,

I have tried to install our amos-eclipse-plugin in eclipse.
I went to 'Help'>'Install New Software'>'Add'>'Archive'

I selected the file "[ABSOLUTE_PATH]/amos-ss15-proj3-eclipse-plugin/target/amos-ss15-proj3-eclipse-plugin-1.0.0.jar"

![struggling_to_install_our_eclipse_plugin](https://cloud.githubusercontent.com/assets/1008351/8162200/16795608-137c-11e5-98c1-485d9c059bb5.png)

What should I do?

**Comment by gayathery** [comment]
Point to plugin project /target/repository

**Comment by GnuTalux** [comment]
sorry, what did you mean with repository?
the jar file?
