### ISSUE TITLE
Req-55 "Requirement description in IDE"

### ISSUE THREAD

**Issue by TPolzer** [uv48uson/amos-ss15-proj3#86]
@GnuTalux please have a look at 08a9d5f58551d4fe46429716085816d57a00e41c and at the sprint backlog. It says there:

As a user I can see the description of requirements in Eclipse so that I can identify requirements more easily.

I am somehow confused how that fits with fd2ca565f33cc4c6f40f3d19972dfb9a005805d9?

**Comment by GnuTalux** [comment]
I thought, that I have to implement Req-55.
But as I see, you have already included it in your implementation. 
Feel free to discard/overwrite my changes :)

**Comment by GnuTalux** [comment]
I hope you don't forget to include the impact value :-)
