### ISSUE TITLE
getting commit id for given filepath

### ISSUE THREAD

**Issue by GnuTalux** [uv48uson/amos-ss15-proj3#92]
Hi guys, 
I am working on Req-68.

As I know ```Tracker.getAllFiles()``` doesn't work correctly, because of showing deleted files and old file paths of moved files.

I think, I should re-implemented ```Tracker.getAllFiles()``` so it iterates over existing project directories and retries for each file path the related commit id. 
Can I use the Method ```GitVcsClient.java#getCommitListForFileodification()``` for this purpose?
I am not absolutely sure, what this method does exactly.

(Most of the code, which I have read, were purely or  uncommented... especially gayatheries code)

**Comment by GnuTalux** [comment]
ok guys, 
maybe I found a solution by my own.
Due to further "investigation" I found following to functions, which sound very promising:
```Tracker.getCommitsFromFile```
```Tracker.getAllRequirementsForFile```

BTW: I would really appreciate, if we try to give our methods similar names.
e.g.: I would have named them:
```Tracker.getCommitsForFile```
```Tracker.getRequirementsForFile```
or
```Tracker.getAllCommitsForFile```
```Tracker.getAllRequirementsForFile```

but, thanks to my powerful IDE, this isn't a very big deal.

**Comment by yadimon** [comment]
there should be more methods like "*getAllCommitFiles()*" or "*getCurrentCommitFiles()*".
if you change tacker, pls be careful with renaming, better way is to let the old method names, mark them `/** @deprecated /*`and inclue there the new methods. Later, in the next sprint, remove the deprecated methods.
Need this because e.g. somebody works with plugin, that uses this methods in own branch. Merge will be hard later, if the methods are not here anymore.

**Comment by GnuTalux** [comment]
Now I have similar issues:
```Tracker.getCommitsFromFile``` and ```Tracker.getAllRequirementsForFile``` doesn't return 
anything :-/ ...

if ```Tracker`` doesn't provides a working function for getting CommitFile, Req or Commit for a given File path, I will implement it by myself.
Does anyone has an idea, why ```Tracker.getCommitsFromFile``` and ```Tracker.getAllRequirementsForFile``` is not returning any result for some file paths?

I am not sure, but is ```GitVcsClient.getCommitListForFileodification``` working correctly?
Everytime, I pass there a absolute path of (let say "$PATH_TO/amos-ss15-proj3/.git") it returns an empty value.
