### ISSUE TITLE
The affect of a requirement on a file is calclated wrong

### ISSUE THREAD

**Issue by KatsiarynaK** [uv48uson/amos-ss15-proj3#95]
If there are empty lines in the file, the application doesnt recognize that they shoul not participate in the  calculation of the affect of a requirement on a file.
for example, if the file has 9 code lines and 1 enpty line, and it was affected by one requrement, the application calculated the affect as 90 % instead of 100%

See example:
http://gyazo.com/dfb88827e37ddd544549badc861cd39e

**Comment by TPolzer** [comment]
This should not be that hard to fix, I will fix it on Friday.
