### ISSUE TITLE
Old issues are back after the refactoring

### ISSUE THREAD

**Issue by KatsiarynaK** [uv48uson/amos-ss15-proj3#96]
The problems described in the user strories 63, 52 are back after the refactoring

**Comment by TPolzer** [comment]
Just for reference, those are:

63: As a user, I want to see only one digit after the comma so that the GUI is not too cluttered.

52: As I user I want the system to store additional information about my requirements, so that I can see more than a requirement ID

**Comment by KatsiarynaK** [comment]
52. As a user, I want to to have a  "left-aligned" alignment of file names in traceability matrix

**Comment by gayathery** [comment]
https://github.com/uv48uson/amos-ss15-proj3/commit/2c5888f01b8383e626cd2d0ec8822136e3e2af6f

https://github.com/uv48uson/amos-ss15-proj3/commit/0b8257b7dd7f75d176650c505aff6eaac95a0f96
